In [74]:

from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.firefox.options import Options
from selenium.webdriver import Firefox
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.common.exceptions import TimeoutException, NoSuchElementException
from selenium.common.exceptions import WebDriverException
from selenium import webdriver
from selenium.webdriver.edge.service import Service
#from selenium.webdriver.edge.options import Options
from urllib.request import urlretrieve




from time import sleep
import warnings
import requests
import pandas as pd
from bs4 import BeautifulSoup
import time
import math
import re
import os

import sqlite3


from datetime import datetime

import numpy as np
import pyodbc as odbc
from sqlalchemy import create_engine
import sqlalchemy as sa

warnings.filterwarnings('ignore')

In [31]:
print(odbc.drivers())
# Ensure the car-brands folder exists
os.makedirs("car-brands", exist_ok=True)

['SQL Server', 'Microsoft Access Driver (*.mdb, *.accdb)', 'Microsoft Excel Driver (*.xls, *.xlsx, *.xlsm, *.xlsb)', 'Microsoft Access Text Driver (*.txt, *.csv)']

#### Second trial method - scraping

In [76]:
# Get the current date
current_date = datetime.now().strftime("%d_%m_%Y")  
cd = datetime.now().strftime("%m_%d_%Y") 
# Capture the start time for postings scraping
start_time_scraping_CG_posts = datetime.now()

# Use EdgeOptions instead of the general Options
# options = Options()
options = webdriver.EdgeOptions()
driver = webdriver.Edge(executable_path='C:/Windows/System32/msedgedriver.exe',options=options)
# Correctly set the binary location for Edge
# options.binary_location = r'C:\Windows\System32\msedge.exe'  # Update with your actual Edge path

options.add_argument("--window-size=1920x1080")
options.add_argument("--headless")
options.add_argument("--verbose")

# Explicitly set the Edge binary location and path to msedgedriver
# service = Service(executable_path=r'C:\Windows\System32\msedgedriver.exe')  # Update with your actual msedgedriver path
# browser = webdriver.Edge(service=service, options=options)
driver.set_page_load_timeout(30)

data = []


URL = f'https://www.carlogos.org/car-brands-a-z/'
driver.get(URL)

all_content = driver.find_element(By.CSS_SELECTOR, 'div.a-z')  # Use find_element to find the container div

dd_elements = all_content.find_elements(By.CSS_SELECTOR, 'dd')  # Get all dd elements

for dd_element in dd_elements:
    try:
        link_element = dd_element.find_element(By.TAG_NAME, 'a')
        brand_name = link_element.text
        print(brand_name)
        brand_link = link_element.get_attribute('href')
        print(brand_link)
    except NoSuchElementException:
        print(f"No link found in the element, skipping: {dd_element.text}")
    else:
        data.append({
            'Brand_name': brand_name,
            'Brand_Content_URL': brand_link
        })

driver.quit()

car_brands_df = pd.DataFrame(data)
print(car_brands_df)

Abadal
https://www.carlogos.org/car-brands/abadal-logo.html
Abarth
https://www.carlogos.org/car-brands/abarth-logo.html
Abbott-Detroit
https://www.carlogos.org/car-brands/abbott-detroit-logo.html
ABT
https://www.carlogos.org/car-brands/abt-sportsline-logo.html
AC
https://www.carlogos.org/car-brands/ac-logo.html
Acura
https://www.carlogos.org/car-brands/acura-logo.html
Aiways
https://www.carlogos.org/car-brands/aiways-logo.html
Aixam
https://www.carlogos.org/car-brands/aixam-logo.html
Alfa Romeo
https://www.carlogos.org/car-brands/alfa-romeo-logo.html
Alpina
https://www.carlogos.org/car-brands/alpina-logo.html
Alpine
https://www.carlogos.org/car-brands/alpine-logo.html
Alta
https://www.carlogos.org/car-brands/alta-logo.html
Alvis
https://www.carlogos.org/car-brands/alvis-logo.html
AMC
https://www.carlogos.org/car-brands/american-motors-logo.html
Apollo
https://www.carlogos.org/car-brands/apollo-logo.html
Arash
https://www.carlogos.org/car-brands/arash-logo.html
Arcfox
https://www.carlogos.org/car-brands/arcfox-logo.html
Ariel
https://www.carlogos.org/car-brands/ariel-logo.html
ARO
https://www.carlogos.org/car-brands/aro-logo.html
Arrival
https://www.carlogos.org/car-brands/arrival-logo.html
Arrinera
https://www.carlogos.org/car-brands/arrinera-logo.html
Artega
https://www.carlogos.org/car-brands/artega-logo.html
Ascari
https://www.carlogos.org/car-brands/ascari-logo.html
Askam
https://www.carlogos.org/car-brands/askam-logo.html
Aspark
https://www.carlogos.org/car-brands/aspark-logo.html
Aston Martin
https://www.carlogos.org/car-brands/aston-martin-logo.html
Atalanta
https://www.carlogos.org/car-brands/atalanta-motors-logo.html
Auburn
https://www.carlogos.org/car-brands/auburn-logo.html
Audi
https://www.carlogos.org/car-brands/audi-logo.html
Audi Sport
https://www.carlogos.org/car-brands/audi-sport-logo.html
Austin
https://www.carlogos.org/car-brands/austin-logo.html
Autobacs
https://www.carlogos.org/car-brands/autobacs-logo.html
Autobianchi
https://www.carlogos.org/car-brands/autobianchi-logo.html
Axon
https://www.carlogos.org/car-brands/axon-logo.html
BAC
https://www.carlogos.org/car-brands/bac-logo.html
BAIC Motor
https://www.carlogos.org/car-brands/baic-logo.html
Baojun
https://www.carlogos.org/car-brands/baojun-logo.html
BeiBen
https://www.carlogos.org/car-brands/beiben-logo.html
Bentley
https://www.carlogos.org/car-brands/bentley-logo.html
Berkeley
https://www.carlogos.org/car-brands/berkeley-logo.html
Berliet
https://www.carlogos.org/car-brands/berliet-logo.html
Bertone
https://www.carlogos.org/car-brands/bertone-logo.html
Bestune
https://www.carlogos.org/car-brands/bestune-logo.html
BharatBenz
https://www.carlogos.org/car-brands/bharatbenz-logo.html
Bitter
https://www.carlogos.org/car-brands/bitter-logo.html
Bizzarrini
https://www.carlogos.org/car-brands/bizzarrini-logo.html
BMW
https://www.carlogos.org/car-brands/bmw-logo.html
BMW M
https://www.carlogos.org/car-brands/bmw-m-logo.html
Borgward
https://www.carlogos.org/car-brands/borgward-logo.html
Bowler
https://www.carlogos.org/car-brands/bowler-logo.html
Brabus
https://www.carlogos.org/car-brands/brabus-logo.html
Brammo
https://www.carlogos.org/car-brands/brammo-logo.html
Brilliance
https://www.carlogos.org/car-brands/brilliance-logo.html
Bristol
https://www.carlogos.org/car-brands/bristol-logo.html
Brooke
https://www.carlogos.org/car-brands/brooke-logo.html
Bufori
https://www.carlogos.org/car-brands/bufori-logo.html
Bugatti
https://www.carlogos.org/car-brands/bugatti-logo.html
Buick
https://www.carlogos.org/car-brands/buick-logo.html
BYD
https://www.carlogos.org/car-brands/byd-logo.html
Byton
https://www.carlogos.org/car-brands/byton-logo.html
Cadillac
https://www.carlogos.org/car-brands/cadillac-logo.html
CAMC
https://www.carlogos.org/car-brands/camc-logo.html
Canoo
https://www.carlogos.org/car-brands/canoo-logo.html
Caparo
https://www.carlogos.org/car-brands/caparo-logo.html
Carlsson
https://www.carlogos.org/car-brands/carlsson-logo.html
Caterham
https://www.carlogos.org/car-brands/caterham-logo.html
Changan
https://www.carlogos.org/car-brands/changan-logo.html
Changfeng
https://www.carlogos.org/car-brands/changfeng-logo.html
Chery
https://www.carlogos.org/car-brands/chery-logo.html
Chevrolet Corvette
https://www.carlogos.org/car-brands/chevrolet-corvette-logo.html
Chevrolet
https://www.carlogos.org/car-brands/chevrolet-logo.html
Chrysler
https://www.carlogos.org/car-brands/chrysler-logo.html
Cisitalia
https://www.carlogos.org/car-brands/cisitalia-logo.html
Citroën
https://www.carlogos.org/car-brands/citroen-logo.html
Cizeta
https://www.carlogos.org/car-brands/cizeta-logo.html
Cole
https://www.carlogos.org/car-brands/cole-logo.html
Corre La Licorne
https://www.carlogos.org/car-brands/corre-la-licorne-logo.html
Dacia
https://www.carlogos.org/car-brands/dacia-logo.html
Daewoo
https://www.carlogos.org/car-brands/daewoo-logo.html
DAF
https://www.carlogos.org/car-brands/daf-logo.html
Daihatsu
https://www.carlogos.org/car-brands/daihatsu-logo.html
Daimler
https://www.carlogos.org/car-brands/daimler-logo.html
Dartz
https://www.carlogos.org/car-brands/dartz-logo.html
Datsun
https://www.carlogos.org/car-brands/datsun-logo.html
David Brown
https://www.carlogos.org/car-brands/david-brown-logo.html
Dayun
https://www.carlogos.org/car-brands/dayun-logo.html
De Tomaso
https://www.carlogos.org/car-brands/de-tomaso-logo.html
Delage
https://www.carlogos.org/car-brands/delage-logo.html
DeSoto
https://www.carlogos.org/car-brands/desoto-logo.html
Detroit Electric
https://www.carlogos.org/car-brands/detroit-electric-logo.html
Devel Sixteen
https://www.carlogos.org/car-brands/devel-sixteen-logo.html
Diatto
https://www.carlogos.org/car-brands/diatto-logo.html
DINA
https://www.carlogos.org/car-brands/dina-logo.html
DKW
https://www.carlogos.org/car-brands/dkw-logo.html
DMC
https://www.carlogos.org/car-brands/delorean-logo.html
Dodge
https://www.carlogos.org/car-brands/dodge-logo.html
Dodge Viper
https://www.carlogos.org/car-brands/dodge-viper-logo.html
Dongfeng
https://www.carlogos.org/car-brands/dongfeng-logo.html
Donkervoort
https://www.carlogos.org/car-brands/donkervoort-logo.html
Drako
https://www.carlogos.org/car-brands/drako-logo.html
DS
https://www.carlogos.org/car-brands/ds-logo.html
Duesenberg
https://www.carlogos.org/car-brands/duesenberg-logo.html
Eagle
https://www.carlogos.org/car-brands/eagle-logo.html
EDAG
https://www.carlogos.org/car-brands/edag-logo.html
Edsel
https://www.carlogos.org/car-brands/edsel-logo.html
Eicher
https://www.carlogos.org/car-brands/eicher-logo.html
Elemental
https://www.carlogos.org/car-brands/elemental-logo.html
Elfin
https://www.carlogos.org/car-brands/elfin-logo.html
Elva
https://www.carlogos.org/car-brands/elva-logo.html
Englon
https://www.carlogos.org/car-brands/englon-logo.html
ERF
https://www.carlogos.org/car-brands/erf-logo.html
Eterniti
https://www.carlogos.org/car-brands/eterniti-logo.html
Exeed
https://www.carlogos.org/car-brands/exeed-logo.html
9ff
https://www.carlogos.org/car-brands/9ff-logo.html
Facel Vega
https://www.carlogos.org/car-brands/facel-vega-logo.html
Faraday Future
https://www.carlogos.org/car-brands/faraday-future-logo.html
FAW
https://www.carlogos.org/car-brands/faw-logo.html
FAW Jiefang
https://www.carlogos.org/car-brands/faw-jiefang-logo.html
Ferrari
https://www.carlogos.org/car-brands/ferrari-logo.html
Fiat
https://www.carlogos.org/car-brands/fiat-logo.html
Fioravanti
https://www.carlogos.org/car-brands/fioravanti-logo.html
Fisker
https://www.carlogos.org/car-brands/fisker-logo.html
Foden
https://www.carlogos.org/car-brands/foden-logo.html
Force Motors
https://www.carlogos.org/car-brands/force-logo.html
Ford
https://www.carlogos.org/car-brands/ford-logo.html
Ford Mustang
https://www.carlogos.org/car-brands/ford-mustang-logo.html
Foton
https://www.carlogos.org/car-brands/foton-logo.html
FPV
https://www.carlogos.org/car-brands/fpv-logo.html
Franklin
https://www.carlogos.org/car-brands/franklin-logo.html
Freightliner
https://www.carlogos.org/car-brands/freightliner-logo.html
FSO
https://www.carlogos.org/car-brands/fso-logo.html
GAC Group
https://www.carlogos.org/car-brands/gac-logo.html
Gardner Douglas
https://www.carlogos.org/car-brands/gardner-douglas-logo.html
GAZ
https://www.carlogos.org/car-brands/gaz-logo.html
Geely
https://www.carlogos.org/car-brands/geely-logo.html
General Motors
https://www.carlogos.org/car-brands/general-motors-logo.html
Genesis
https://www.carlogos.org/car-brands/genesis-logo.html
Geo
https://www.carlogos.org/car-brands/geo-logo.html
Geometry
https://www.carlogos.org/car-brands/geometry-logo.html
Gilbern
https://www.carlogos.org/car-brands/gilbern-logo.html
Gillet
https://www.carlogos.org/car-brands/gillet-logo.html
Ginetta
https://www.carlogos.org/car-brands/ginetta-logo.html
GMC
https://www.carlogos.org/car-brands/gmc-logo.html
Golden Dragon
https://www.carlogos.org/car-brands/golden-dragon-logo.html
Gonow
https://www.carlogos.org/car-brands/gonow-logo.html
Great Wall
https://www.carlogos.org/car-brands/great-wall-logo.html
Grinnall
https://www.carlogos.org/car-brands/grinnall-logo.html
Gumpert
https://www.carlogos.org/car-brands/gumpert-logo.html
Hafei
https://www.carlogos.org/car-brands/hafei-logo.html
Haima
https://www.carlogos.org/car-brands/haima-logo.html
Haval
https://www.carlogos.org/car-brands/haval-logo.html
Hawtai
https://www.carlogos.org/car-brands/hawtai-logo.html
Hennessey
https://www.carlogos.org/car-brands/hennessey-logo.html
Hillman
https://www.carlogos.org/car-brands/hillman-logo.html
Hindustan Motors
https://www.carlogos.org/car-brands/hindustan-logo.html
Higer
https://www.carlogos.org/car-brands/higer-logo.html
Hino
https://www.carlogos.org/car-brands/hino-logo.html
HiPhi
https://www.carlogos.org/car-brands/hiphi-logo.html
Hispano-Suiza
https://www.carlogos.org/car-brands/hispano-suiza-logo.html
Holden
https://www.carlogos.org/car-brands/holden-logo.html
Hommell
https://www.carlogos.org/car-brands/hommell-logo.html
Honda
https://www.carlogos.org/car-brands/honda-logo.html
Hongqi
https://www.carlogos.org/car-brands/hongqi-logo.html
Hongyan
https://www.carlogos.org/car-brands/hongyan-logo.html
Horch
https://www.carlogos.org/car-brands/horch-logo.html
HSV
https://www.carlogos.org/car-brands/hsv-logo.html
Hudson
https://www.carlogos.org/car-brands/hudson-logo.html
Hummer
https://www.carlogos.org/car-brands/hummer-logo.html
Hupmobile
https://www.carlogos.org/car-brands/hupmobile-logo.html
Hyundai
https://www.carlogos.org/car-brands/hyundai-logo.html
IC Bus
https://www.carlogos.org/car-brands/ic-bus-logo.html
Infiniti
https://www.carlogos.org/car-brands/infiniti-logo.html
Innocenti
https://www.carlogos.org/car-brands/innocenti-logo.html
Intermeccanica
https://www.carlogos.org/car-brands/intermeccanica-logo.html
IH
https://www.carlogos.org/car-brands/international-harvester-logo.html
International
https://www.carlogos.org/car-brands/international-logo.html
IKCO
https://www.carlogos.org/car-brands/iran-khodro-logo.html
Irizar
https://www.carlogos.org/car-brands/irizar-logo.html
Isdera
https://www.carlogos.org/car-brands/isdera-logo.html
Iso
https://www.carlogos.org/car-brands/iso-logo.html
Isuzu
https://www.carlogos.org/car-brands/isuzu-logo.html
Iveco
https://www.carlogos.org/car-brands/iveco-logo.html
JAC
https://www.carlogos.org/car-brands/jac-logo.html
Jaguar
https://www.carlogos.org/car-brands/jaguar-logo.html
Jawa
https://www.carlogos.org/car-brands/jawa-logo.html
JBA Motors
https://www.carlogos.org/car-brands/jba-motors-logo.html
Jeep
https://www.carlogos.org/car-brands/jeep-logo.html
Jensen
https://www.carlogos.org/car-brands/jensen-logo.html
Jetta
https://www.carlogos.org/car-brands/jetta-logo.html
JMC
https://www.carlogos.org/car-brands/jiangling-logo.html
Kaiser
https://www.carlogos.org/car-brands/kaiser-logo.html
Kamaz
https://www.carlogos.org/car-brands/kamaz-logo.html
Karlmann King
https://www.carlogos.org/car-brands/karlmann-king-logo.html
Karma
https://www.carlogos.org/car-brands/karma-logo.html
Keating
https://www.carlogos.org/car-brands/keating-logo.html
Kenworth
https://www.carlogos.org/car-brands/kenworth-logo.html
Kia
https://www.carlogos.org/car-brands/kia-logo.html
King Long
https://www.carlogos.org/car-brands/king-long-logo.html
Koenigsegg
https://www.carlogos.org/car-brands/koenigsegg-logo.html
KTM
https://www.carlogos.org/car-brands/ktm-logo.html
Lada
https://www.carlogos.org/car-brands/lada-logo.html
Lagonda
https://www.carlogos.org/car-brands/lagonda-logo.html
Lamborghini
https://www.carlogos.org/car-brands/lamborghini-logo.html
Lancia
https://www.carlogos.org/car-brands/lancia-logo.html
Land Rover
https://www.carlogos.org/car-brands/land-rover-logo.html
Landwind
https://www.carlogos.org/car-brands/landwind-logo.html
Laraki
https://www.carlogos.org/car-brands/laraki-logo.html
Leapmotor
https://www.carlogos.org/car-brands/leapmotor-logo.html
Lexus
https://www.carlogos.org/car-brands/lexus-logo.html
Leyland
https://www.carlogos.org/car-brands/leyland-logo.html
Li Auto
https://www.carlogos.org/car-brands/lixiang-logo.html
Lifan
https://www.carlogos.org/car-brands/lifan-logo.html
Ligier
https://www.carlogos.org/car-brands/ligier-logo.html
Lincoln
https://www.carlogos.org/car-brands/lincoln-logo.html
Lister
https://www.carlogos.org/car-brands/lister-logo.html
Lloyd
https://www.carlogos.org/car-brands/lloyd-logo.html
Lobini
https://www.carlogos.org/car-brands/lobini-logo.html
LEVC
https://www.carlogos.org/car-brands/london-ev-company-logo.html
Lordstown
https://www.carlogos.org/car-brands/lordstown-logo.html
Lotus
https://www.carlogos.org/car-brands/lotus-logo.html
Lucid
https://www.carlogos.org/car-brands/lucid-logo.html
Luxgen
https://www.carlogos.org/car-brands/luxgen-logo.html
Lynk & Co
https://www.carlogos.org/car-brands/lynkco-logo.html
Mack
https://www.carlogos.org/car-brands/mack-logo.html
Mahindra
https://www.carlogos.org/car-brands/mahindra-logo.html
MAN
https://www.carlogos.org/car-brands/man-logo.html
Mansory
https://www.carlogos.org/car-brands/mansory-logo.html
Marcos
https://www.carlogos.org/car-brands/marcos-logo.html
Marlin
https://www.carlogos.org/car-brands/marlin-logo.html
Maserati
https://www.carlogos.org/car-brands/maserati-logo.html
Mastretta
https://www.carlogos.org/car-brands/mastretta-logo.html
Maxus
https://www.carlogos.org/car-brands/maxus-logo.html
Maybach
https://www.carlogos.org/car-brands/maybach-logo.html
MAZ
https://www.carlogos.org/car-brands/maz-logo.html
Mazda
https://www.carlogos.org/car-brands/mazda-logo.html
Mazzanti
https://www.carlogos.org/car-brands/mazzanti-logo.html
McLaren
https://www.carlogos.org/car-brands/mclaren-logo.html
Melkus
https://www.carlogos.org/car-brands/melkus-logo.html
Mercedes-AMG
https://www.carlogos.org/car-brands/mercedes-amg-logo.html
Mercedes-Benz
https://www.carlogos.org/car-brands/mercedes-benz-logo.html
Mercury
https://www.carlogos.org/car-brands/mercury-logo.html
Merkur
https://www.carlogos.org/car-brands/merkur-logo.html
MEV
https://www.carlogos.org/car-brands/mev-logo.html
MG
https://www.carlogos.org/car-brands/mg-logo.html
Microcar
https://www.carlogos.org/car-brands/microcar-logo.html
Mini
https://www.carlogos.org/car-brands/mini-logo.html
Mitsubishi
https://www.carlogos.org/car-brands/mitsubishi-logo.html
Mitsuoka
https://www.carlogos.org/car-brands/mitsuoka-logo.html
MK
https://www.carlogos.org/car-brands/mk-sportscars-logo.html
Morgan
https://www.carlogos.org/car-brands/morgan-logo.html
Morris
https://www.carlogos.org/car-brands/morris-logo.html
Mosler
https://www.carlogos.org/car-brands/mosler-logo.html
Navistar
https://www.carlogos.org/car-brands/navistar-logo.html
NEVS
https://www.carlogos.org/car-brands/nevs-logo.html
NIO
https://www.carlogos.org/car-brands/nio-logo.html
Nikola
https://www.carlogos.org/car-brands/nikola-logo.html
Nissan GT-R
https://www.carlogos.org/car-brands/nissan-gt-r-logo.html
Nissan
https://www.carlogos.org/car-brands/nissan-logo.html
Nissan Nismo
https://www.carlogos.org/car-brands/nissan-nismo-logo.html
Noble
https://www.carlogos.org/car-brands/noble-logo.html
Oldsmobile
https://www.carlogos.org/car-brands/oldsmobile-logo.html
Oltcit
https://www.carlogos.org/car-brands/oltcit-logo.html
Opel
https://www.carlogos.org/car-brands/opel-logo.html
OSCA
https://www.carlogos.org/car-brands/osca-logo.html
Paccar
https://www.carlogos.org/car-brands/paccar-logo.html
Packard
https://www.carlogos.org/car-brands/packard-logo.html
Pagani
https://www.carlogos.org/car-brands/pagani-logo.html
Panhard
https://www.carlogos.org/car-brands/panhard-logo.html
Panoz
https://www.carlogos.org/car-brands/panoz-logo.html
Pegaso
https://www.carlogos.org/car-brands/pegaso-logo.html
Perodua
https://www.carlogos.org/car-brands/perodua-logo.html
Peterbilt
https://www.carlogos.org/car-brands/peterbilt-logo.html
Peugeot
https://www.carlogos.org/car-brands/peugeot-logo.html
PGO
https://www.carlogos.org/car-brands/pgo-logo.html
Pierce-Arrow
https://www.carlogos.org/car-brands/pierce-arrow-logo.html
Pininfarina
https://www.carlogos.org/car-brands/pininfarina-logo.html
Plymouth
https://www.carlogos.org/car-brands/plymouth-logo.html
Polestar
https://www.carlogos.org/car-brands/polestar-logo.html
Pontiac
https://www.carlogos.org/car-brands/pontiac-logo.html
Porsche
https://www.carlogos.org/car-brands/porsche-logo.html
Praga
https://www.carlogos.org/car-brands/praga-logo.html
Premier
https://www.carlogos.org/car-brands/premier-logo.html
Prodrive
https://www.carlogos.org/car-brands/prodrive-logo.html
Proton
https://www.carlogos.org/car-brands/proton-logo.html
Qoros
https://www.carlogos.org/car-brands/qoros-logo.html
Radical
https://www.carlogos.org/car-brands/radical-logo.html
RAM
https://www.carlogos.org/car-brands/ram-logo.html
Rambler
https://www.carlogos.org/car-brands/rambler-logo.html
Ranz
https://www.carlogos.org/car-brands/ranz-logo.html
Renault
https://www.carlogos.org/car-brands/renault-logo.html
Renault Samsung
https://www.carlogos.org/car-brands/renault-samsung-logo.html
Rezvani
https://www.carlogos.org/car-brands/rezvani-logo.html
Riley
https://www.carlogos.org/car-brands/riley-logo.html
Rimac
https://www.carlogos.org/car-brands/rimac-logo.html
Rinspeed
https://www.carlogos.org/car-brands/rinspeed-logo.html
Rivian
https://www.carlogos.org/car-brands/rivian-logo.html
Roewe
https://www.carlogos.org/car-brands/roewe-logo.html
Rolls-Royce
https://www.carlogos.org/car-brands/rolls-royce-logo.html
Ronart
https://www.carlogos.org/car-brands/ronart-logo.html
Rossion
https://www.carlogos.org/car-brands/rossion-logo.html
Rover
https://www.carlogos.org/car-brands/rover-logo.html
RUF
https://www.carlogos.org/car-brands/ruf-logo.html
Saab
https://www.carlogos.org/car-brands/saab-logo.html
SAIC Motor
https://www.carlogos.org/car-brands/saic-motor-logo.html
Saipa
https://www.carlogos.org/car-brands/saipa-logo.html
Saleen
https://www.carlogos.org/car-brands/saleen-logo.html
Saturn
https://www.carlogos.org/car-brands/saturn-logo.html
Scania
https://www.carlogos.org/car-brands/scania-logo.html
Scion
https://www.carlogos.org/car-brands/scion-logo.html
SEAT
https://www.carlogos.org/car-brands/seat-logo.html
Setra
https://www.carlogos.org/car-brands/setra-logo.html
Shacman
https://www.carlogos.org/car-brands/shacman-logo.html
Simca
https://www.carlogos.org/car-brands/simca-logo.html
Singer
https://www.carlogos.org/car-brands/singer-logo.html
Singulato
https://www.carlogos.org/car-brands/singulato-logo.html
Sinotruk
https://www.carlogos.org/car-brands/sinotruk-logo.html
Sisu
https://www.carlogos.org/car-brands/sisu-logo.html
Škoda
https://www.carlogos.org/car-brands/skoda-logo.html
Smart
https://www.carlogos.org/car-brands/smart-logo.html
Soueast
https://www.carlogos.org/car-brands/soueast-logo.html
Spania GTA
https://www.carlogos.org/car-brands/spania-gta-logo.html
Spirra
https://www.carlogos.org/car-brands/spirra-logo.html
Spyker
https://www.carlogos.org/car-brands/spyker-logo.html
SsangYong
https://www.carlogos.org/car-brands/ssangyong-logo.html
SSC

In [77]:
len(car_brands_df)

383

In [78]:
car_brands_df.tail()

    Brand_name                                  Brand_Content_URL
378      Zenos  https://www.carlogos.org/car-brands/zenos-logo...
379      Zenvo  https://www.carlogos.org/car-brands/zenvo-logo...
380  Zhongtong  https://www.carlogos.org/car-brands/zhongtong-...
381     Zinoro  https://www.carlogos.org/car-brands/zhinuo-log...
382      Zotye  https://www.carlogos.org/car-brands/zotye-logo...

In [79]:
car_brands_df['Brand_Content_URL'][4]

'https://www.carlogos.org/car-brands/ac-logo.html'

In [83]:

# ... (Your other imports and setup remain the same)

def logo_link(url, brand_name):
    """Downloads and saves the logo image from the given URL.

    Args:
        url (str): The URL of the webpage containing the logo.
        brand_name (str): The name of the brand.

    Returns:
        str or None: The filename of the saved image, or None if an error occurred.
    """
    # Use EdgeOptions instead of the general Options
    # options = Options()
    options = webdriver.EdgeOptions()
    driver = webdriver.Edge(executable_path='C:/Windows/System32/msedgedriver.exe',options=options)
    options.add_argument("--window-size=1920x1080")
    options.add_argument("--headless")
    options.add_argument("--verbose")
    driver.set_page_load_timeout(30)

    try:
            driver.get(url)

            brand_content = driver.find_element(By.CSS_SELECTOR, "div.content")
            logo_link_element = brand_content.find_element(By.TAG_NAME, "a")
            return logo_link_element.get_attribute('href')
    except Exception as e:
        print(f"Error processing {brand_name}: {e}")
        return None
    finally:
        driver.quit()  # Close the driver after processing each URL

# ... (Your code to scrape brand names and URLs into car_brands_df) ...
# Assuming your DataFrame has a column named 'Brand_Content_URL'

In [84]:
car_brands_df['Brand_logo_URL'] = car_brands_df['Brand_Content_URL'].apply(
    lambda url: logo_link(url, car_brands_df.loc[car_brands_df['Brand_Content_URL'] == url, 'Brand_name'].iloc[0]) 
)

Error processing Aiways: Message: no such element: Unable to locate element: {"method":"css selector","selector":"div.content"}
  (Session info: MicrosoftEdge=126.0.2592.113)
Stacktrace:
	GetHandleVerifier [0x008736A3+37027]
	Microsoft::Applications::Events::time_ticks_t::time_ticks_t [0x0073FD26+400614]
	Microsoft::Applications::Events::ILogConfiguration::operator* [0x00546DA6+3558]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x0057A6FE+107742]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x0057A87D+108125]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x005A6482+287330]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x00590294+196724]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x00573DB1+80785]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x005A4DD0+281520]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x0058FEB6+195734]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x005735B3+78739]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x005725A5+74629]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x00572FBD+77213]
	GetHandleVerifier [0x0096C0AC+1055404]
	Microsoft::Applications::Events::FromJSON [0x00A446A7+154215]
	Microsoft::Applications::Events::FromJSON [0x00A44047+152583]
	Microsoft::Applications::Events::FromJSON [0x00A34C00+90048]
	Microsoft::Applications::Events::FromJSON [0x00A44EAB+156267]
	Microsoft::Applications::Events::time_ticks_t::time_ticks_t [0x007550BF+487551]
	Microsoft::Applications::Events::time_ticks_t::time_ticks_t [0x007492D8+438936]
	Microsoft::Applications::Events::time_ticks_t::time_ticks_t [0x0074944B+439307]
	Microsoft::Applications::Events::time_ticks_t::time_ticks_t [0x007318BA+342138]
	BaseThreadInitThunk [0x765B7BA9+25]
	RtlInitializeExceptionChain [0x7709C10B+107]
	RtlClearBits [0x7709C08F+191]

Error processing Alta: Message: no such element: Unable to locate element: {"method":"tag name","selector":"a"}
  (Session info: MicrosoftEdge=126.0.2592.113)
Stacktrace:
	GetHandleVerifier [0x008736A3+37027]
	Microsoft::Applications::Events::time_ticks_t::time_ticks_t [0x0073FD26+400614]
	Microsoft::Applications::Events::ILogConfiguration::operator* [0x00546DA6+3558]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x0057A6FE+107742]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x0057A87D+108125]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x00573E01+80865]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x00590294+196724]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x00573DB1+80785]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x00573D30+80656]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x00590574+197460]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x00573DB1+80785]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x005A4DD0+281520]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x0058FEB6+195734]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x005735B3+78739]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x005725A5+74629]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x00572FBD+77213]
	GetHandleVerifier [0x0096C0AC+1055404]
	Microsoft::Applications::Events::FromJSON [0x00A446A7+154215]
	Microsoft::Applications::Events::FromJSON [0x00A44047+152583]
	Microsoft::Applications::Events::FromJSON [0x00A34C00+90048]
	Microsoft::Applications::Events::FromJSON [0x00A44EAB+156267]
	Microsoft::Applications::Events::time_ticks_t::time_ticks_t [0x007550BF+487551]
	Microsoft::Applications::Events::time_ticks_t::time_ticks_t [0x007492D8+438936]
	Microsoft::Applications::Events::time_ticks_t::time_ticks_t [0x0074944B+439307]
	Microsoft::Applications::Events::time_ticks_t::time_ticks_t [0x007318BA+342138]
	BaseThreadInitThunk [0x765B7BA9+25]
	RtlInitializeExceptionChain [0x7709C10B+107]
	RtlClearBits [0x7709C08F+191]

Error processing Arcfox: Message: no such element: Unable to locate element: {"method":"css selector","selector":"div.content"}
  (Session info: MicrosoftEdge=126.0.2592.113)
Stacktrace:
	GetHandleVerifier [0x008736A3+37027]
	Microsoft::Applications::Events::time_ticks_t::time_ticks_t [0x0073FD26+400614]
	Microsoft::Applications::Events::ILogConfiguration::operator* [0x00546DA6+3558]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x0057A6FE+107742]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x0057A87D+108125]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x005A6482+287330]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x00590294+196724]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x00573DB1+80785]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x005A4DD0+281520]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x0058FEB6+195734]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x005735B3+78739]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x005725A5+74629]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x00572FBD+77213]
	GetHandleVerifier [0x0096C0AC+1055404]
	Microsoft::Applications::Events::FromJSON [0x00A446A7+154215]
	Microsoft::Applications::Events::FromJSON [0x00A44047+152583]
	Microsoft::Applications::Events::FromJSON [0x00A34C00+90048]
	Microsoft::Applications::Events::FromJSON [0x00A44EAB+156267]
	Microsoft::Applications::Events::time_ticks_t::time_ticks_t [0x007550BF+487551]
	Microsoft::Applications::Events::time_ticks_t::time_ticks_t [0x007492D8+438936]
	Microsoft::Applications::Events::time_ticks_t::time_ticks_t [0x0074944B+439307]
	Microsoft::Applications::Events::time_ticks_t::time_ticks_t [0x007318BA+342138]
	BaseThreadInitThunk [0x765B7BA9+25]
	RtlInitializeExceptionChain [0x7709C10B+107]
	RtlClearBits [0x7709C08F+191]

Error processing Arrival: Message: no such element: Unable to locate element: {"method":"css selector","selector":"div.content"}
  (Session info: MicrosoftEdge=126.0.2592.113)
Stacktrace:
	GetHandleVerifier [0x008736A3+37027]
	Microsoft::Applications::Events::time_ticks_t::time_ticks_t [0x0073FD26+400614]
	Microsoft::Applications::Events::ILogConfiguration::operator* [0x00546DA6+3558]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x0057A6FE+107742]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x0057A87D+108125]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x005A6482+287330]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x00590294+196724]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x00573DB1+80785]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x005A4DD0+281520]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x0058FEB6+195734]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x005735B3+78739]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x005725A5+74629]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x00572FBD+77213]
	GetHandleVerifier [0x0096C0AC+1055404]
	Microsoft::Applications::Events::FromJSON [0x00A446A7+154215]
	Microsoft::Applications::Events::FromJSON [0x00A44047+152583]
	Microsoft::Applications::Events::FromJSON [0x00A34C00+90048]
	Microsoft::Applications::Events::FromJSON [0x00A44EAB+156267]
	Microsoft::Applications::Events::time_ticks_t::time_ticks_t [0x007550BF+487551]
	Microsoft::Applications::Events::time_ticks_t::time_ticks_t [0x007492D8+438936]
	Microsoft::Applications::Events::time_ticks_t::time_ticks_t [0x0074944B+439307]
	Microsoft::Applications::Events::time_ticks_t::time_ticks_t [0x007318BA+342138]
	BaseThreadInitThunk [0x765B7BA9+25]
	RtlInitializeExceptionChain [0x7709C10B+107]
	RtlClearBits [0x7709C08F+191]

Error processing Aspark: Message: no such element: Unable to locate element: {"method":"css selector","selector":"div.content"}
  (Session info: MicrosoftEdge=126.0.2592.113)
Stacktrace:
	GetHandleVerifier [0x008736A3+37027]
	Microsoft::Applications::Events::time_ticks_t::time_ticks_t [0x0073FD26+400614]
	Microsoft::Applications::Events::ILogConfiguration::operator* [0x00546DA6+3558]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x0057A6FE+107742]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x0057A87D+108125]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x005A6482+287330]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x00590294+196724]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x00573DB1+80785]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x005A4DD0+281520]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x0058FEB6+195734]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x005735B3+78739]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x005725A5+74629]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x00572FBD+77213]
	GetHandleVerifier [0x0096C0AC+1055404]
	Microsoft::Applications::Events::FromJSON [0x00A446A7+154215]
	Microsoft::Applications::Events::FromJSON [0x00A44047+152583]
	Microsoft::Applications::Events::FromJSON [0x00A34C00+90048]
	Microsoft::Applications::Events::FromJSON [0x00A44EAB+156267]
	Microsoft::Applications::Events::time_ticks_t::time_ticks_t [0x007550BF+487551]
	Microsoft::Applications::Events::time_ticks_t::time_ticks_t [0x007492D8+438936]
	Microsoft::Applications::Events::time_ticks_t::time_ticks_t [0x0074944B+439307]
	Microsoft::Applications::Events::time_ticks_t::time_ticks_t [0x007318BA+342138]
	BaseThreadInitThunk [0x765B7BA9+25]
	RtlInitializeExceptionChain [0x7709C10B+107]
	RtlClearBits [0x7709C08F+191]

Error processing Audi: Message: no such element: Unable to locate element: {"method":"css selector","selector":"div.content"}
  (Session info: MicrosoftEdge=126.0.2592.113)
Stacktrace:
	GetHandleVerifier [0x008736A3+37027]
	Microsoft::Applications::Events::time_ticks_t::time_ticks_t [0x0073FD26+400614]
	Microsoft::Applications::Events::ILogConfiguration::operator* [0x00546DA6+3558]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x0057A6FE+107742]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x0057A87D+108125]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x005A6482+287330]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x00590294+196724]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x00573DB1+80785]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x005A4DD0+281520]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x0058FEB6+195734]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x005735B3+78739]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x005725A5+74629]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x00572FBD+77213]
	GetHandleVerifier [0x0096C0AC+1055404]
	Microsoft::Applications::Events::FromJSON [0x00A446A7+154215]
	Microsoft::Applications::Events::FromJSON [0x00A44047+152583]
	Microsoft::Applications::Events::FromJSON [0x00A34C00+90048]
	Microsoft::Applications::Events::FromJSON [0x00A44EAB+156267]
	Microsoft::Applications::Events::time_ticks_t::time_ticks_t [0x007550BF+487551]
	Microsoft::Applications::Events::time_ticks_t::time_ticks_t [0x007492D8+438936]
	Microsoft::Applications::Events::time_ticks_t::time_ticks_t [0x0074944B+439307]
	Microsoft::Applications::Events::time_ticks_t::time_ticks_t [0x007318BA+342138]
	BaseThreadInitThunk [0x765B7BA9+25]
	RtlInitializeExceptionChain [0x7709C10B+107]
	RtlClearBits [0x7709C08F+191]

Error processing BeiBen: Message: no such element: Unable to locate element: {"method":"css selector","selector":"div.content"}
  (Session info: MicrosoftEdge=126.0.2592.113)
Stacktrace:
	GetHandleVerifier [0x008736A3+37027]
	Microsoft::Applications::Events::time_ticks_t::time_ticks_t [0x0073FD26+400614]
	Microsoft::Applications::Events::ILogConfiguration::operator* [0x00546DA6+3558]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x0057A6FE+107742]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x0057A87D+108125]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x005A6482+287330]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x00590294+196724]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x00573DB1+80785]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x005A4DD0+281520]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x0058FEB6+195734]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x005735B3+78739]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x005725A5+74629]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x00572FBD+77213]
	GetHandleVerifier [0x0096C0AC+1055404]
	Microsoft::Applications::Events::FromJSON [0x00A446A7+154215]
	Microsoft::Applications::Events::FromJSON [0x00A44047+152583]
	Microsoft::Applications::Events::FromJSON [0x00A34C00+90048]
	Microsoft::Applications::Events::FromJSON [0x00A44EAB+156267]
	Microsoft::Applications::Events::time_ticks_t::time_ticks_t [0x007550BF+487551]
	Microsoft::Applications::Events::time_ticks_t::time_ticks_t [0x007492D8+438936]
	Microsoft::Applications::Events::time_ticks_t::time_ticks_t [0x0074944B+439307]
	Microsoft::Applications::Events::time_ticks_t::time_ticks_t [0x007318BA+342138]
	BaseThreadInitThunk [0x765B7BA9+25]
	RtlInitializeExceptionChain [0x7709C10B+107]
	RtlClearBits [0x7709C08F+191]

Error processing Bentley: Message: no such element: Unable to locate element: {"method":"css selector","selector":"div.content"}
  (Session info: MicrosoftEdge=126.0.2592.113)
Stacktrace:
	GetHandleVerifier [0x008736A3+37027]
	Microsoft::Applications::Events::time_ticks_t::time_ticks_t [0x0073FD26+400614]
	Microsoft::Applications::Events::ILogConfiguration::operator* [0x00546DA6+3558]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x0057A6FE+107742]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x0057A87D+108125]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x005A6482+287330]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x00590294+196724]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x00573DB1+80785]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x005A4DD0+281520]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x0058FEB6+195734]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x005735B3+78739]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x005725A5+74629]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x00572FBD+77213]
	GetHandleVerifier [0x0096C0AC+1055404]
	Microsoft::Applications::Events::FromJSON [0x00A446A7+154215]
	Microsoft::Applications::Events::FromJSON [0x00A44047+152583]
	Microsoft::Applications::Events::FromJSON [0x00A34C00+90048]
	Microsoft::Applications::Events::FromJSON [0x00A44EAB+156267]
	Microsoft::Applications::Events::time_ticks_t::time_ticks_t [0x007550BF+487551]
	Microsoft::Applications::Events::time_ticks_t::time_ticks_t [0x007492D8+438936]
	Microsoft::Applications::Events::time_ticks_t::time_ticks_t [0x0074944B+439307]
	Microsoft::Applications::Events::time_ticks_t::time_ticks_t [0x007318BA+342138]
	BaseThreadInitThunk [0x765B7BA9+25]
	RtlInitializeExceptionChain [0x7709C10B+107]
	RtlClearBits [0x7709C08F+191]

Error processing Bestune: Message: no such element: Unable to locate element: {"method":"css selector","selector":"div.content"}
  (Session info: MicrosoftEdge=126.0.2592.113)
Stacktrace:
	GetHandleVerifier [0x008736A3+37027]
	Microsoft::Applications::Events::time_ticks_t::time_ticks_t [0x0073FD26+400614]
	Microsoft::Applications::Events::ILogConfiguration::operator* [0x00546DA6+3558]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x0057A6FE+107742]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x0057A87D+108125]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x005A6482+287330]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x00590294+196724]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x00573DB1+80785]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x005A4DD0+281520]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x0058FEB6+195734]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x005735B3+78739]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x005725A5+74629]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x00572FBD+77213]
	GetHandleVerifier [0x0096C0AC+1055404]
	Microsoft::Applications::Events::FromJSON [0x00A446A7+154215]
	Microsoft::Applications::Events::FromJSON [0x00A44047+152583]
	Microsoft::Applications::Events::FromJSON [0x00A34C00+90048]
	Microsoft::Applications::Events::FromJSON [0x00A44EAB+156267]
	Microsoft::Applications::Events::time_ticks_t::time_ticks_t [0x007550BF+487551]
	Microsoft::Applications::Events::time_ticks_t::time_ticks_t [0x007492D8+438936]
	Microsoft::Applications::Events::time_ticks_t::time_ticks_t [0x0074944B+439307]
	Microsoft::Applications::Events::time_ticks_t::time_ticks_t [0x007318BA+342138]
	BaseThreadInitThunk [0x765B7BA9+25]
	RtlInitializeExceptionChain [0x7709C10B+107]
	RtlClearBits [0x7709C08F+191]

Error processing BMW: Message: no such element: Unable to locate element: {"method":"css selector","selector":"div.content"}
  (Session info: MicrosoftEdge=126.0.2592.113)
Stacktrace:
	GetHandleVerifier [0x008736A3+37027]
	Microsoft::Applications::Events::time_ticks_t::time_ticks_t [0x0073FD26+400614]
	Microsoft::Applications::Events::ILogConfiguration::operator* [0x00546DA6+3558]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x0057A6FE+107742]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x0057A87D+108125]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x005A6482+287330]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x00590294+196724]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x00573DB1+80785]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x005A4DD0+281520]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x0058FEB6+195734]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x005735B3+78739]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x005725A5+74629]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x00572FBD+77213]
	GetHandleVerifier [0x0096C0AC+1055404]
	Microsoft::Applications::Events::FromJSON [0x00A446A7+154215]
	Microsoft::Applications::Events::FromJSON [0x00A44047+152583]
	Microsoft::Applications::Events::FromJSON [0x00A34C00+90048]
	Microsoft::Applications::Events::FromJSON [0x00A44EAB+156267]
	Microsoft::Applications::Events::time_ticks_t::time_ticks_t [0x007550BF+487551]
	Microsoft::Applications::Events::time_ticks_t::time_ticks_t [0x007492D8+438936]
	Microsoft::Applications::Events::time_ticks_t::time_ticks_t [0x0074944B+439307]
	Microsoft::Applications::Events::time_ticks_t::time_ticks_t [0x007318BA+342138]
	BaseThreadInitThunk [0x765B7BA9+25]
	RtlInitializeExceptionChain [0x7709C10B+107]
	RtlClearBits [0x7709C08F+191]

Error processing Byton: Message: no such element: Unable to locate element: {"method":"css selector","selector":"div.content"}
  (Session info: MicrosoftEdge=126.0.2592.113)
Stacktrace:
	GetHandleVerifier [0x008736A3+37027]
	Microsoft::Applications::Events::time_ticks_t::time_ticks_t [0x0073FD26+400614]
	Microsoft::Applications::Events::ILogConfiguration::operator* [0x00546DA6+3558]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x0057A6FE+107742]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x0057A87D+108125]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x005A6482+287330]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x00590294+196724]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x00573DB1+80785]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x005A4DD0+281520]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x0058FEB6+195734]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x005735B3+78739]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x005725A5+74629]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x00572FBD+77213]
	GetHandleVerifier [0x0096C0AC+1055404]
	Microsoft::Applications::Events::FromJSON [0x00A446A7+154215]
	Microsoft::Applications::Events::FromJSON [0x00A44047+152583]
	Microsoft::Applications::Events::FromJSON [0x00A34C00+90048]
	Microsoft::Applications::Events::FromJSON [0x00A44EAB+156267]
	Microsoft::Applications::Events::time_ticks_t::time_ticks_t [0x007550BF+487551]
	Microsoft::Applications::Events::time_ticks_t::time_ticks_t [0x007492D8+438936]
	Microsoft::Applications::Events::time_ticks_t::time_ticks_t [0x0074944B+439307]
	Microsoft::Applications::Events::time_ticks_t::time_ticks_t [0x007318BA+342138]
	BaseThreadInitThunk [0x765B7BA9+25]
	RtlInitializeExceptionChain [0x7709C10B+107]

In [85]:
car_brands_df['Brand_logo_URL'].nunique()

282

In [92]:
# 1. Count Missing Values:
num_missing = car_brands_df['Brand_logo_URL'].isnull().sum()
print(f"Number of missing Brand_logo_URL values: {num_missing}")

Number of missing Brand_logo_URL values: 73

In [88]:
car_brands_df.head()

,Brand_name,Brand_Content_URL,Brand_logo_URL
0,Abadal,https://www.carlogos.org/car-brands/abadal-log...,https://www.carlogos.org/logo/Abadal-logo-1920...
1,Abarth,https://www.carlogos.org/car-brands/abarth-log...,https://www.carlogos.org/logo/Abarth-logo-1920...
2,Abbott-Detroit,https://www.carlogos.org/car-brands/abbott-det...,https://www.carlogos.org/american-car-brands/
3,ABT,https://www.carlogos.org/car-brands/abt-sports...,https://www.carlogos.org/logo/ABT-Sportsline-l...
4,AC,https://www.carlogos.org/car-brands/ac-logo.html,https://www.carlogos.org/logo/AC-logo-1920x108...

In [93]:

# 2. Filter Rows with Missing Values:
missing_rows = car_brands_df[car_brands_df['Brand_logo_URL'].isnull()].copy()

# 3. Apply `logo_link` Only to Missing Rows:
missing_rows['Brand_logo_URL'] = missing_rows['Brand_Content_URL'].apply(
    lambda url: logo_link(url, missing_rows.loc[missing_rows['Brand_Content_URL'] == url, 'Brand_name'].iloc[0])
)

# 4. Update Original DataFrame:
# Merge the updated `missing_rows` back into the original DataFrame based on index.
# This preserves the order of the original DataFrame and avoids dropping any rows.
car_brands_df.update(missing_rows)

Error processing Aiways: Message: no such element: Unable to locate element: {"method":"css selector","selector":"div.content"}
  (Session info: MicrosoftEdge=126.0.2592.113)
Stacktrace:
	GetHandleVerifier [0x008736A3+37027]
	Microsoft::Applications::Events::time_ticks_t::time_ticks_t [0x0073FD26+400614]
	Microsoft::Applications::Events::ILogConfiguration::operator* [0x00546DA6+3558]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x0057A6FE+107742]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x0057A87D+108125]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x005A6482+287330]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x00590294+196724]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x00573DB1+80785]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x005A4DD0+281520]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x0058FEB6+195734]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x005735B3+78739]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x005725A5+74629]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x00572FBD+77213]
	GetHandleVerifier [0x0096C0AC+1055404]
	Microsoft::Applications::Events::FromJSON [0x00A446A7+154215]
	Microsoft::Applications::Events::FromJSON [0x00A44047+152583]
	Microsoft::Applications::Events::FromJSON [0x00A34C00+90048]
	Microsoft::Applications::Events::FromJSON [0x00A44EAB+156267]
	Microsoft::Applications::Events::time_ticks_t::time_ticks_t [0x007550BF+487551]
	Microsoft::Applications::Events::time_ticks_t::time_ticks_t [0x007492D8+438936]
	Microsoft::Applications::Events::time_ticks_t::time_ticks_t [0x0074944B+439307]
	Microsoft::Applications::Events::time_ticks_t::time_ticks_t [0x007318BA+342138]
	BaseThreadInitThunk [0x765B7BA9+25]
	RtlInitializeExceptionChain [0x7709C10B+107]
	RtlClearBits [0x7709C08F+191]

Error processing Alta: Message: no such element: Unable to locate element: {"method":"tag name","selector":"a"}
  (Session info: MicrosoftEdge=126.0.2592.113)
Stacktrace:
	GetHandleVerifier [0x008736A3+37027]
	Microsoft::Applications::Events::time_ticks_t::time_ticks_t [0x0073FD26+400614]
	Microsoft::Applications::Events::ILogConfiguration::operator* [0x00546DA6+3558]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x0057A6FE+107742]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x0057A87D+108125]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x00573E01+80865]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x00590294+196724]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x00573DB1+80785]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x00573D30+80656]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x00590574+197460]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x00573DB1+80785]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x005A4DD0+281520]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x0058FEB6+195734]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x005735B3+78739]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x005725A5+74629]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x00572FBD+77213]
	GetHandleVerifier [0x0096C0AC+1055404]
	Microsoft::Applications::Events::FromJSON [0x00A446A7+154215]
	Microsoft::Applications::Events::FromJSON [0x00A44047+152583]
	Microsoft::Applications::Events::FromJSON [0x00A34C00+90048]
	Microsoft::Applications::Events::FromJSON [0x00A44EAB+156267]
	Microsoft::Applications::Events::time_ticks_t::time_ticks_t [0x007550BF+487551]
	Microsoft::Applications::Events::time_ticks_t::time_ticks_t [0x007492D8+438936]
	Microsoft::Applications::Events::time_ticks_t::time_ticks_t [0x0074944B+439307]
	Microsoft::Applications::Events::time_ticks_t::time_ticks_t [0x007318BA+342138]
	BaseThreadInitThunk [0x765B7BA9+25]
	RtlInitializeExceptionChain [0x7709C10B+107]
	RtlClearBits [0x7709C08F+191]

Error processing Arcfox: Message: no such element: Unable to locate element: {"method":"css selector","selector":"div.content"}
  (Session info: MicrosoftEdge=126.0.2592.113)
Stacktrace:
	GetHandleVerifier [0x008736A3+37027]
	Microsoft::Applications::Events::time_ticks_t::time_ticks_t [0x0073FD26+400614]
	Microsoft::Applications::Events::ILogConfiguration::operator* [0x00546DA6+3558]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x0057A6FE+107742]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x0057A87D+108125]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x005A6482+287330]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x00590294+196724]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x00573DB1+80785]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x005A4DD0+281520]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x0058FEB6+195734]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x005735B3+78739]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x005725A5+74629]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x00572FBD+77213]
	GetHandleVerifier [0x0096C0AC+1055404]
	Microsoft::Applications::Events::FromJSON [0x00A446A7+154215]
	Microsoft::Applications::Events::FromJSON [0x00A44047+152583]
	Microsoft::Applications::Events::FromJSON [0x00A34C00+90048]
	Microsoft::Applications::Events::FromJSON [0x00A44EAB+156267]
	Microsoft::Applications::Events::time_ticks_t::time_ticks_t [0x007550BF+487551]
	Microsoft::Applications::Events::time_ticks_t::time_ticks_t [0x007492D8+438936]
	Microsoft::Applications::Events::time_ticks_t::time_ticks_t [0x0074944B+439307]
	Microsoft::Applications::Events::time_ticks_t::time_ticks_t [0x007318BA+342138]
	BaseThreadInitThunk [0x765B7BA9+25]
	RtlInitializeExceptionChain [0x7709C10B+107]
	RtlClearBits [0x7709C08F+191]

Error processing Arrival: Message: no such element: Unable to locate element: {"method":"css selector","selector":"div.content"}
  (Session info: MicrosoftEdge=126.0.2592.113)
Stacktrace:
	GetHandleVerifier [0x008736A3+37027]
	Microsoft::Applications::Events::time_ticks_t::time_ticks_t [0x0073FD26+400614]
	Microsoft::Applications::Events::ILogConfiguration::operator* [0x00546DA6+3558]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x0057A6FE+107742]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x0057A87D+108125]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x005A6482+287330]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x00590294+196724]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x00573DB1+80785]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x005A4DD0+281520]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x0058FEB6+195734]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x005735B3+78739]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x005725A5+74629]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x00572FBD+77213]
	GetHandleVerifier [0x0096C0AC+1055404]
	Microsoft::Applications::Events::FromJSON [0x00A446A7+154215]
	Microsoft::Applications::Events::FromJSON [0x00A44047+152583]
	Microsoft::Applications::Events::FromJSON [0x00A34C00+90048]
	Microsoft::Applications::Events::FromJSON [0x00A44EAB+156267]
	Microsoft::Applications::Events::time_ticks_t::time_ticks_t [0x007550BF+487551]
	Microsoft::Applications::Events::time_ticks_t::time_ticks_t [0x007492D8+438936]
	Microsoft::Applications::Events::time_ticks_t::time_ticks_t [0x0074944B+439307]
	Microsoft::Applications::Events::time_ticks_t::time_ticks_t [0x007318BA+342138]
	BaseThreadInitThunk [0x765B7BA9+25]
	RtlInitializeExceptionChain [0x7709C10B+107]
	RtlClearBits [0x7709C08F+191]

Error processing Aspark: Message: no such element: Unable to locate element: {"method":"css selector","selector":"div.content"}
  (Session info: MicrosoftEdge=126.0.2592.113)
Stacktrace:
	GetHandleVerifier [0x008736A3+37027]
	Microsoft::Applications::Events::time_ticks_t::time_ticks_t [0x0073FD26+400614]
	Microsoft::Applications::Events::ILogConfiguration::operator* [0x00546DA6+3558]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x0057A6FE+107742]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x0057A87D+108125]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x005A6482+287330]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x00590294+196724]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x00573DB1+80785]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x005A4DD0+281520]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x0058FEB6+195734]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x005735B3+78739]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x005725A5+74629]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x00572FBD+77213]
	GetHandleVerifier [0x0096C0AC+1055404]
	Microsoft::Applications::Events::FromJSON [0x00A446A7+154215]
	Microsoft::Applications::Events::FromJSON [0x00A44047+152583]
	Microsoft::Applications::Events::FromJSON [0x00A34C00+90048]
	Microsoft::Applications::Events::FromJSON [0x00A44EAB+156267]
	Microsoft::Applications::Events::time_ticks_t::time_ticks_t [0x007550BF+487551]
	Microsoft::Applications::Events::time_ticks_t::time_ticks_t [0x007492D8+438936]
	Microsoft::Applications::Events::time_ticks_t::time_ticks_t [0x0074944B+439307]
	Microsoft::Applications::Events::time_ticks_t::time_ticks_t [0x007318BA+342138]
	BaseThreadInitThunk [0x765B7BA9+25]
	RtlInitializeExceptionChain [0x7709C10B+107]
	RtlClearBits [0x7709C08F+191]

Error processing Audi: Message: no such element: Unable to locate element: {"method":"css selector","selector":"div.content"}
  (Session info: MicrosoftEdge=126.0.2592.113)
Stacktrace:
	GetHandleVerifier [0x008736A3+37027]
	Microsoft::Applications::Events::time_ticks_t::time_ticks_t [0x0073FD26+400614]
	Microsoft::Applications::Events::ILogConfiguration::operator* [0x00546DA6+3558]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x0057A6FE+107742]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x0057A87D+108125]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x005A6482+287330]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x00590294+196724]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x00573DB1+80785]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x005A4DD0+281520]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x0058FEB6+195734]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x005735B3+78739]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x005725A5+74629]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x00572FBD+77213]
	GetHandleVerifier [0x0096C0AC+1055404]
	Microsoft::Applications::Events::FromJSON [0x00A446A7+154215]
	Microsoft::Applications::Events::FromJSON [0x00A44047+152583]
	Microsoft::Applications::Events::FromJSON [0x00A34C00+90048]
	Microsoft::Applications::Events::FromJSON [0x00A44EAB+156267]
	Microsoft::Applications::Events::time_ticks_t::time_ticks_t [0x007550BF+487551]
	Microsoft::Applications::Events::time_ticks_t::time_ticks_t [0x007492D8+438936]
	Microsoft::Applications::Events::time_ticks_t::time_ticks_t [0x0074944B+439307]
	Microsoft::Applications::Events::time_ticks_t::time_ticks_t [0x007318BA+342138]
	BaseThreadInitThunk [0x765B7BA9+25]
	RtlInitializeExceptionChain [0x7709C10B+107]
	RtlClearBits [0x7709C08F+191]

Error processing BeiBen: Message: no such element: Unable to locate element: {"method":"css selector","selector":"div.content"}
  (Session info: MicrosoftEdge=126.0.2592.113)
Stacktrace:
	GetHandleVerifier [0x008736A3+37027]
	Microsoft::Applications::Events::time_ticks_t::time_ticks_t [0x0073FD26+400614]
	Microsoft::Applications::Events::ILogConfiguration::operator* [0x00546DA6+3558]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x0057A6FE+107742]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x0057A87D+108125]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x005A6482+287330]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x00590294+196724]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x00573DB1+80785]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x005A4DD0+281520]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x0058FEB6+195734]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x005735B3+78739]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x005725A5+74629]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x00572FBD+77213]
	GetHandleVerifier [0x0096C0AC+1055404]
	Microsoft::Applications::Events::FromJSON [0x00A446A7+154215]
	Microsoft::Applications::Events::FromJSON [0x00A44047+152583]
	Microsoft::Applications::Events::FromJSON [0x00A34C00+90048]
	Microsoft::Applications::Events::FromJSON [0x00A44EAB+156267]
	Microsoft::Applications::Events::time_ticks_t::time_ticks_t [0x007550BF+487551]
	Microsoft::Applications::Events::time_ticks_t::time_ticks_t [0x007492D8+438936]
	Microsoft::Applications::Events::time_ticks_t::time_ticks_t [0x0074944B+439307]
	Microsoft::Applications::Events::time_ticks_t::time_ticks_t [0x007318BA+342138]
	BaseThreadInitThunk [0x765B7BA9+25]
	RtlInitializeExceptionChain [0x7709C10B+107]
	RtlClearBits [0x7709C08F+191]

Error processing Bentley: Message: no such element: Unable to locate element: {"method":"css selector","selector":"div.content"}
  (Session info: MicrosoftEdge=126.0.2592.113)
Stacktrace:
	GetHandleVerifier [0x008736A3+37027]
	Microsoft::Applications::Events::time_ticks_t::time_ticks_t [0x0073FD26+400614]
	Microsoft::Applications::Events::ILogConfiguration::operator* [0x00546DA6+3558]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x0057A6FE+107742]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x0057A87D+108125]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x005A6482+287330]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x00590294+196724]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x00573DB1+80785]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x005A4DD0+281520]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x0058FEB6+195734]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x005735B3+78739]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x005725A5+74629]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x00572FBD+77213]
	GetHandleVerifier [0x0096C0AC+1055404]
	Microsoft::Applications::Events::FromJSON [0x00A446A7+154215]
	Microsoft::Applications::Events::FromJSON [0x00A44047+152583]
	Microsoft::Applications::Events::FromJSON [0x00A34C00+90048]
	Microsoft::Applications::Events::FromJSON [0x00A44EAB+156267]
	Microsoft::Applications::Events::time_ticks_t::time_ticks_t [0x007550BF+487551]
	Microsoft::Applications::Events::time_ticks_t::time_ticks_t [0x007492D8+438936]
	Microsoft::Applications::Events::time_ticks_t::time_ticks_t [0x0074944B+439307]
	Microsoft::Applications::Events::time_ticks_t::time_ticks_t [0x007318BA+342138]
	BaseThreadInitThunk [0x765B7BA9+25]
	RtlInitializeExceptionChain [0x7709C10B+107]
	RtlClearBits [0x7709C08F+191]

Error processing Bestune: Message: no such element: Unable to locate element: {"method":"css selector","selector":"div.content"}
  (Session info: MicrosoftEdge=126.0.2592.113)
Stacktrace:
	GetHandleVerifier [0x008736A3+37027]
	Microsoft::Applications::Events::time_ticks_t::time_ticks_t [0x0073FD26+400614]
	Microsoft::Applications::Events::ILogConfiguration::operator* [0x00546DA6+3558]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x0057A6FE+107742]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x0057A87D+108125]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x005A6482+287330]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x00590294+196724]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x00573DB1+80785]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x005A4DD0+281520]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x0058FEB6+195734]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x005735B3+78739]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x005725A5+74629]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x00572FBD+77213]
	GetHandleVerifier [0x0096C0AC+1055404]
	Microsoft::Applications::Events::FromJSON [0x00A446A7+154215]
	Microsoft::Applications::Events::FromJSON [0x00A44047+152583]
	Microsoft::Applications::Events::FromJSON [0x00A34C00+90048]
	Microsoft::Applications::Events::FromJSON [0x00A44EAB+156267]
	Microsoft::Applications::Events::time_ticks_t::time_ticks_t [0x007550BF+487551]
	Microsoft::Applications::Events::time_ticks_t::time_ticks_t [0x007492D8+438936]
	Microsoft::Applications::Events::time_ticks_t::time_ticks_t [0x0074944B+439307]
	Microsoft::Applications::Events::time_ticks_t::time_ticks_t [0x007318BA+342138]
	BaseThreadInitThunk [0x765B7BA9+25]
	RtlInitializeExceptionChain [0x7709C10B+107]
	RtlClearBits [0x7709C08F+191]

Error processing BMW: Message: no such element: Unable to locate element: {"method":"css selector","selector":"div.content"}
  (Session info: MicrosoftEdge=126.0.2592.113)
Stacktrace:
	GetHandleVerifier [0x008736A3+37027]
	Microsoft::Applications::Events::time_ticks_t::time_ticks_t [0x0073FD26+400614]
	Microsoft::Applications::Events::ILogConfiguration::operator* [0x00546DA6+3558]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x0057A6FE+107742]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x0057A87D+108125]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x005A6482+287330]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x00590294+196724]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x00573DB1+80785]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x005A4DD0+281520]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x0058FEB6+195734]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x005735B3+78739]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x005725A5+74629]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x00572FBD+77213]
	GetHandleVerifier [0x0096C0AC+1055404]
	Microsoft::Applications::Events::FromJSON [0x00A446A7+154215]
	Microsoft::Applications::Events::FromJSON [0x00A44047+152583]
	Microsoft::Applications::Events::FromJSON [0x00A34C00+90048]
	Microsoft::Applications::Events::FromJSON [0x00A44EAB+156267]
	Microsoft::Applications::Events::time_ticks_t::time_ticks_t [0x007550BF+487551]
	Microsoft::Applications::Events::time_ticks_t::time_ticks_t [0x007492D8+438936]
	Microsoft::Applications::Events::time_ticks_t::time_ticks_t [0x0074944B+439307]
	Microsoft::Applications::Events::time_ticks_t::time_ticks_t [0x007318BA+342138]
	BaseThreadInitThunk [0x765B7BA9+25]
	RtlInitializeExceptionChain [0x7709C10B+107]
	RtlClearBits [0x7709C08F+191]

Error processing Byton: Message: no such element: Unable to locate element: {"method":"css selector","selector":"div.content"}
  (Session info: MicrosoftEdge=126.0.2592.113)
Stacktrace:
	GetHandleVerifier [0x008736A3+37027]
	Microsoft::Applications::Events::time_ticks_t::time_ticks_t [0x0073FD26+400614]
	Microsoft::Applications::Events::ILogConfiguration::operator* [0x00546DA6+3558]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x0057A6FE+107742]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x0057A87D+108125]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x005A6482+287330]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x00590294+196724]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x00573DB1+80785]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x005A4DD0+281520]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x0058FEB6+195734]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x005735B3+78739]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x005725A5+74629]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x00572FBD+77213]
	GetHandleVerifier [0x0096C0AC+1055404]
	Microsoft::Applications::Events::FromJSON [0x00A446A7+154215]
	Microsoft::Applications::Events::FromJSON [0x00A44047+152583]
	Microsoft::Applications::Events::FromJSON [0x00A34C00+90048]
	Microsoft::Applications::Events::FromJSON [0x00A44EAB+156267]
	Microsoft::Applications::Events::time_ticks_t::time_ticks_t [0x007550BF+487551]
	Microsoft::Applications::Events::time_ticks_t::time_ticks_t [0x007492D8+438936]
	Microsoft::Applications::Events::time_ticks_t::time_ticks_t [0x0074944B+439307]
	Microsoft::Applications::Events::time_ticks_t::time_ticks_t [0x007318BA+342138]
	BaseThreadInitThunk [0x765B7BA9+25]
	RtlInitializeExceptionChain [0x7709C10B+107]

In [94]:
# 1. Count Missing Values:
num_missing = car_brands_df['Brand_logo_URL'].isnull().sum()
print(f"Number of missing Brand_logo_URL values: {num_missing}")

Number of missing Brand_logo_URL values: 73

In [102]:
missing_logo_brands = car_brands_df[car_brands_df['Brand_logo_URL'].isnull()]

# Get unique brand names with missing logos
unique_missing_brands = missing_logo_brands['Brand_name'].unique()

# Print the unique brand names
print("Brands with missing logos:")
for brand in unique_missing_brands:
    print(brand)

Brands with missing logos:
Aiways
Arcfox
Arrival
Aspark
Audi
BeiBen
Bentley
Bestune
BMW
Byton
Cadillac
CAMC
Canoo
Chevrolet Corvette
Chrysler
Dayun
DeSoto
Dodge
Drako
Duesenberg
Exeed
FAW Jiefang
Ferrari
Ford
FSO
Geometry
Golden Dragon
Higer
HiPhi
Honda
Hongqi
Hongyan
Hyundai
Jaguar
Jeep
Jetta
Karlmann King
King Long
Lamborghini
Leapmotor
Li Auto
Lordstown
Lynk & Co
Maserati
Mazda
NEVS
NIO
Nikola
Nissan
Packard
Porsche
Rivian
Shacman
Singulato
Sinotruk
Stutz
Subaru
Tesla
Toyota Alphard
Toyota Century
Toyota
Tucker
VinFast
VLF
Weltmeister
WEY
Workhorse
XPeng
Yutong
Zeekr
Zhongtong
Zinoro

In [99]:

# ... (Your other imports and setup remain the same)

def logo_link2(url, brand_name):
    """Downloads and saves the logo image from the given URL.

    Args:
        url (str): The URL of the webpage containing the logo.
        brand_name (str): The name of the brand.

    Returns:
        str or None: The filename of the saved image, or None if an error occurred.
    """
    # Use EdgeOptions instead of the general Options
    # options = Options()
    options = webdriver.EdgeOptions()
    driver = webdriver.Edge(executable_path='C:/Windows/System32/msedgedriver.exe',options=options)
    options.add_argument("--window-size=1920x1080")
    options.add_argument("--headless")
    options.add_argument("--verbose")
    driver.set_page_load_timeout(30)

    try:
            driver.get(url)

            brand_content = driver.find_element(By.CSS_SELECTOR, "div.content")
            logo_link_element = brand_content.find_element(By.TAG_NAME, "img")
            return logo_link_element.get_attribute('src')
    except Exception as e:
        print(f"Error processing {brand_name}: {e}")
        return None
    finally:
        driver.quit()  # Close the driver after processing each URL

# ... (Your code to scrape brand names and URLs into car_brands_df) ...
# Assuming your DataFrame has a column named 'Brand_Content_URL'

In [100]:

# 2. Filter Rows with Missing Values:
missing_rows = car_brands_df[car_brands_df['Brand_logo_URL'].isnull()].copy()

# 3. Apply `logo_link` Only to Missing Rows:
missing_rows['Brand_logo_URL'] = missing_rows['Brand_Content_URL'].apply(
    lambda url: logo_link2(url, missing_rows.loc[missing_rows['Brand_Content_URL'] == url, 'Brand_name'].iloc[0])
)

# 4. Update Original DataFrame:
# Merge the updated `missing_rows` back into the original DataFrame based on index.
# This preserves the order of the original DataFrame and avoids dropping any rows.
car_brands_df.update(missing_rows)

Error processing Aiways: Message: no such element: Unable to locate element: {"method":"css selector","selector":"div.content"}
  (Session info: MicrosoftEdge=126.0.2592.113)
Stacktrace:
	GetHandleVerifier [0x008736A3+37027]
	Microsoft::Applications::Events::time_ticks_t::time_ticks_t [0x0073FD26+400614]
	Microsoft::Applications::Events::ILogConfiguration::operator* [0x00546DA6+3558]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x0057A6FE+107742]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x0057A87D+108125]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x005A6482+287330]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x00590294+196724]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x00573DB1+80785]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x005A4DD0+281520]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x0058FEB6+195734]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x005735B3+78739]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x005725A5+74629]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x00572FBD+77213]
	GetHandleVerifier [0x0096C0AC+1055404]
	Microsoft::Applications::Events::FromJSON [0x00A446A7+154215]
	Microsoft::Applications::Events::FromJSON [0x00A44047+152583]
	Microsoft::Applications::Events::FromJSON [0x00A34C00+90048]
	Microsoft::Applications::Events::FromJSON [0x00A44EAB+156267]
	Microsoft::Applications::Events::time_ticks_t::time_ticks_t [0x007550BF+487551]
	Microsoft::Applications::Events::time_ticks_t::time_ticks_t [0x007492D8+438936]
	Microsoft::Applications::Events::time_ticks_t::time_ticks_t [0x0074944B+439307]
	Microsoft::Applications::Events::time_ticks_t::time_ticks_t [0x007318BA+342138]
	BaseThreadInitThunk [0x765B7BA9+25]
	RtlInitializeExceptionChain [0x7709C10B+107]
	RtlClearBits [0x7709C08F+191]

Error processing Arcfox: Message: no such element: Unable to locate element: {"method":"css selector","selector":"div.content"}
  (Session info: MicrosoftEdge=126.0.2592.113)
Stacktrace:
	GetHandleVerifier [0x008736A3+37027]
	Microsoft::Applications::Events::time_ticks_t::time_ticks_t [0x0073FD26+400614]
	Microsoft::Applications::Events::ILogConfiguration::operator* [0x00546DA6+3558]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x0057A6FE+107742]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x0057A87D+108125]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x005A6482+287330]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x00590294+196724]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x00573DB1+80785]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x005A4DD0+281520]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x0058FEB6+195734]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x005735B3+78739]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x005725A5+74629]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x00572FBD+77213]
	GetHandleVerifier [0x0096C0AC+1055404]
	Microsoft::Applications::Events::FromJSON [0x00A446A7+154215]
	Microsoft::Applications::Events::FromJSON [0x00A44047+152583]
	Microsoft::Applications::Events::FromJSON [0x00A34C00+90048]
	Microsoft::Applications::Events::FromJSON [0x00A44EAB+156267]
	Microsoft::Applications::Events::time_ticks_t::time_ticks_t [0x007550BF+487551]
	Microsoft::Applications::Events::time_ticks_t::time_ticks_t [0x007492D8+438936]
	Microsoft::Applications::Events::time_ticks_t::time_ticks_t [0x0074944B+439307]
	Microsoft::Applications::Events::time_ticks_t::time_ticks_t [0x007318BA+342138]
	BaseThreadInitThunk [0x765B7BA9+25]
	RtlInitializeExceptionChain [0x7709C10B+107]
	RtlClearBits [0x7709C08F+191]

Error processing Arrival: Message: no such element: Unable to locate element: {"method":"css selector","selector":"div.content"}
  (Session info: MicrosoftEdge=126.0.2592.113)
Stacktrace:
	GetHandleVerifier [0x008736A3+37027]
	Microsoft::Applications::Events::time_ticks_t::time_ticks_t [0x0073FD26+400614]
	Microsoft::Applications::Events::ILogConfiguration::operator* [0x00546DA6+3558]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x0057A6FE+107742]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x0057A87D+108125]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x005A6482+287330]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x00590294+196724]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x00573DB1+80785]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x005A4DD0+281520]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x0058FEB6+195734]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x005735B3+78739]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x005725A5+74629]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x00572FBD+77213]
	GetHandleVerifier [0x0096C0AC+1055404]
	Microsoft::Applications::Events::FromJSON [0x00A446A7+154215]
	Microsoft::Applications::Events::FromJSON [0x00A44047+152583]
	Microsoft::Applications::Events::FromJSON [0x00A34C00+90048]
	Microsoft::Applications::Events::FromJSON [0x00A44EAB+156267]
	Microsoft::Applications::Events::time_ticks_t::time_ticks_t [0x007550BF+487551]
	Microsoft::Applications::Events::time_ticks_t::time_ticks_t [0x007492D8+438936]
	Microsoft::Applications::Events::time_ticks_t::time_ticks_t [0x0074944B+439307]
	Microsoft::Applications::Events::time_ticks_t::time_ticks_t [0x007318BA+342138]
	BaseThreadInitThunk [0x765B7BA9+25]
	RtlInitializeExceptionChain [0x7709C10B+107]
	RtlClearBits [0x7709C08F+191]

Error processing Aspark: Message: no such element: Unable to locate element: {"method":"css selector","selector":"div.content"}
  (Session info: MicrosoftEdge=126.0.2592.113)
Stacktrace:
	GetHandleVerifier [0x008736A3+37027]
	Microsoft::Applications::Events::time_ticks_t::time_ticks_t [0x0073FD26+400614]
	Microsoft::Applications::Events::ILogConfiguration::operator* [0x00546DA6+3558]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x0057A6FE+107742]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x0057A87D+108125]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x005A6482+287330]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x00590294+196724]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x00573DB1+80785]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x005A4DD0+281520]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x0058FEB6+195734]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x005735B3+78739]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x005725A5+74629]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x00572FBD+77213]
	GetHandleVerifier [0x0096C0AC+1055404]
	Microsoft::Applications::Events::FromJSON [0x00A446A7+154215]
	Microsoft::Applications::Events::FromJSON [0x00A44047+152583]
	Microsoft::Applications::Events::FromJSON [0x00A34C00+90048]
	Microsoft::Applications::Events::FromJSON [0x00A44EAB+156267]
	Microsoft::Applications::Events::time_ticks_t::time_ticks_t [0x007550BF+487551]
	Microsoft::Applications::Events::time_ticks_t::time_ticks_t [0x007492D8+438936]
	Microsoft::Applications::Events::time_ticks_t::time_ticks_t [0x0074944B+439307]
	Microsoft::Applications::Events::time_ticks_t::time_ticks_t [0x007318BA+342138]
	BaseThreadInitThunk [0x765B7BA9+25]
	RtlInitializeExceptionChain [0x7709C10B+107]
	RtlClearBits [0x7709C08F+191]

Error processing Audi: Message: no such element: Unable to locate element: {"method":"css selector","selector":"div.content"}
  (Session info: MicrosoftEdge=126.0.2592.113)
Stacktrace:
	GetHandleVerifier [0x008736A3+37027]
	Microsoft::Applications::Events::time_ticks_t::time_ticks_t [0x0073FD26+400614]
	Microsoft::Applications::Events::ILogConfiguration::operator* [0x00546DA6+3558]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x0057A6FE+107742]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x0057A87D+108125]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x005A6482+287330]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x00590294+196724]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x00573DB1+80785]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x005A4DD0+281520]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x0058FEB6+195734]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x005735B3+78739]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x005725A5+74629]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x00572FBD+77213]
	GetHandleVerifier [0x0096C0AC+1055404]
	Microsoft::Applications::Events::FromJSON [0x00A446A7+154215]
	Microsoft::Applications::Events::FromJSON [0x00A44047+152583]
	Microsoft::Applications::Events::FromJSON [0x00A34C00+90048]
	Microsoft::Applications::Events::FromJSON [0x00A44EAB+156267]
	Microsoft::Applications::Events::time_ticks_t::time_ticks_t [0x007550BF+487551]
	Microsoft::Applications::Events::time_ticks_t::time_ticks_t [0x007492D8+438936]
	Microsoft::Applications::Events::time_ticks_t::time_ticks_t [0x0074944B+439307]
	Microsoft::Applications::Events::time_ticks_t::time_ticks_t [0x007318BA+342138]
	BaseThreadInitThunk [0x765B7BA9+25]
	RtlInitializeExceptionChain [0x7709C10B+107]
	RtlClearBits [0x7709C08F+191]

Error processing BeiBen: Message: no such element: Unable to locate element: {"method":"css selector","selector":"div.content"}
  (Session info: MicrosoftEdge=126.0.2592.113)
Stacktrace:
	GetHandleVerifier [0x008736A3+37027]
	Microsoft::Applications::Events::time_ticks_t::time_ticks_t [0x0073FD26+400614]
	Microsoft::Applications::Events::ILogConfiguration::operator* [0x00546DA6+3558]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x0057A6FE+107742]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x0057A87D+108125]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x005A6482+287330]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x00590294+196724]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x00573DB1+80785]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x005A4DD0+281520]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x0058FEB6+195734]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x005735B3+78739]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x005725A5+74629]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x00572FBD+77213]
	GetHandleVerifier [0x0096C0AC+1055404]
	Microsoft::Applications::Events::FromJSON [0x00A446A7+154215]
	Microsoft::Applications::Events::FromJSON [0x00A44047+152583]
	Microsoft::Applications::Events::FromJSON [0x00A34C00+90048]
	Microsoft::Applications::Events::FromJSON [0x00A44EAB+156267]
	Microsoft::Applications::Events::time_ticks_t::time_ticks_t [0x007550BF+487551]
	Microsoft::Applications::Events::time_ticks_t::time_ticks_t [0x007492D8+438936]
	Microsoft::Applications::Events::time_ticks_t::time_ticks_t [0x0074944B+439307]
	Microsoft::Applications::Events::time_ticks_t::time_ticks_t [0x007318BA+342138]
	BaseThreadInitThunk [0x765B7BA9+25]
	RtlInitializeExceptionChain [0x7709C10B+107]
	RtlClearBits [0x7709C08F+191]

Error processing Bentley: Message: no such element: Unable to locate element: {"method":"css selector","selector":"div.content"}
  (Session info: MicrosoftEdge=126.0.2592.113)
Stacktrace:
	GetHandleVerifier [0x008736A3+37027]
	Microsoft::Applications::Events::time_ticks_t::time_ticks_t [0x0073FD26+400614]
	Microsoft::Applications::Events::ILogConfiguration::operator* [0x00546DA6+3558]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x0057A6FE+107742]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x0057A87D+108125]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x005A6482+287330]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x00590294+196724]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x00573DB1+80785]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x005A4DD0+281520]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x0058FEB6+195734]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x005735B3+78739]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x005725A5+74629]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x00572FBD+77213]
	GetHandleVerifier [0x0096C0AC+1055404]
	Microsoft::Applications::Events::FromJSON [0x00A446A7+154215]
	Microsoft::Applications::Events::FromJSON [0x00A44047+152583]
	Microsoft::Applications::Events::FromJSON [0x00A34C00+90048]
	Microsoft::Applications::Events::FromJSON [0x00A44EAB+156267]
	Microsoft::Applications::Events::time_ticks_t::time_ticks_t [0x007550BF+487551]
	Microsoft::Applications::Events::time_ticks_t::time_ticks_t [0x007492D8+438936]
	Microsoft::Applications::Events::time_ticks_t::time_ticks_t [0x0074944B+439307]
	Microsoft::Applications::Events::time_ticks_t::time_ticks_t [0x007318BA+342138]
	BaseThreadInitThunk [0x765B7BA9+25]
	RtlInitializeExceptionChain [0x7709C10B+107]
	RtlClearBits [0x7709C08F+191]

Error processing Bestune: Message: no such element: Unable to locate element: {"method":"css selector","selector":"div.content"}
  (Session info: MicrosoftEdge=126.0.2592.113)
Stacktrace:
	GetHandleVerifier [0x008736A3+37027]
	Microsoft::Applications::Events::time_ticks_t::time_ticks_t [0x0073FD26+400614]
	Microsoft::Applications::Events::ILogConfiguration::operator* [0x00546DA6+3558]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x0057A6FE+107742]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x0057A87D+108125]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x005A6482+287330]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x00590294+196724]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x00573DB1+80785]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x005A4DD0+281520]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x0058FEB6+195734]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x005735B3+78739]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x005725A5+74629]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x00572FBD+77213]
	GetHandleVerifier [0x0096C0AC+1055404]
	Microsoft::Applications::Events::FromJSON [0x00A446A7+154215]
	Microsoft::Applications::Events::FromJSON [0x00A44047+152583]
	Microsoft::Applications::Events::FromJSON [0x00A34C00+90048]
	Microsoft::Applications::Events::FromJSON [0x00A44EAB+156267]
	Microsoft::Applications::Events::time_ticks_t::time_ticks_t [0x007550BF+487551]
	Microsoft::Applications::Events::time_ticks_t::time_ticks_t [0x007492D8+438936]
	Microsoft::Applications::Events::time_ticks_t::time_ticks_t [0x0074944B+439307]
	Microsoft::Applications::Events::time_ticks_t::time_ticks_t [0x007318BA+342138]
	BaseThreadInitThunk [0x765B7BA9+25]
	RtlInitializeExceptionChain [0x7709C10B+107]
	RtlClearBits [0x7709C08F+191]

Error processing BMW: Message: no such element: Unable to locate element: {"method":"css selector","selector":"div.content"}
  (Session info: MicrosoftEdge=126.0.2592.113)
Stacktrace:
	GetHandleVerifier [0x008736A3+37027]
	Microsoft::Applications::Events::time_ticks_t::time_ticks_t [0x0073FD26+400614]
	Microsoft::Applications::Events::ILogConfiguration::operator* [0x00546DA6+3558]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x0057A6FE+107742]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x0057A87D+108125]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x005A6482+287330]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x00590294+196724]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x00573DB1+80785]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x005A4DD0+281520]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x0058FEB6+195734]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x005735B3+78739]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x005725A5+74629]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x00572FBD+77213]
	GetHandleVerifier [0x0096C0AC+1055404]
	Microsoft::Applications::Events::FromJSON [0x00A446A7+154215]
	Microsoft::Applications::Events::FromJSON [0x00A44047+152583]
	Microsoft::Applications::Events::FromJSON [0x00A34C00+90048]
	Microsoft::Applications::Events::FromJSON [0x00A44EAB+156267]
	Microsoft::Applications::Events::time_ticks_t::time_ticks_t [0x007550BF+487551]
	Microsoft::Applications::Events::time_ticks_t::time_ticks_t [0x007492D8+438936]
	Microsoft::Applications::Events::time_ticks_t::time_ticks_t [0x0074944B+439307]
	Microsoft::Applications::Events::time_ticks_t::time_ticks_t [0x007318BA+342138]
	BaseThreadInitThunk [0x765B7BA9+25]
	RtlInitializeExceptionChain [0x7709C10B+107]
	RtlClearBits [0x7709C08F+191]

Error processing Byton: Message: no such element: Unable to locate element: {"method":"css selector","selector":"div.content"}
  (Session info: MicrosoftEdge=126.0.2592.113)
Stacktrace:
	GetHandleVerifier [0x008736A3+37027]
	Microsoft::Applications::Events::time_ticks_t::time_ticks_t [0x0073FD26+400614]
	Microsoft::Applications::Events::ILogConfiguration::operator* [0x00546DA6+3558]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x0057A6FE+107742]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x0057A87D+108125]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x005A6482+287330]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x00590294+196724]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x00573DB1+80785]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x005A4DD0+281520]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x0058FEB6+195734]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x005735B3+78739]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x005725A5+74629]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x00572FBD+77213]
	GetHandleVerifier [0x0096C0AC+1055404]
	Microsoft::Applications::Events::FromJSON [0x00A446A7+154215]
	Microsoft::Applications::Events::FromJSON [0x00A44047+152583]
	Microsoft::Applications::Events::FromJSON [0x00A34C00+90048]
	Microsoft::Applications::Events::FromJSON [0x00A44EAB+156267]
	Microsoft::Applications::Events::time_ticks_t::time_ticks_t [0x007550BF+487551]
	Microsoft::Applications::Events::time_ticks_t::time_ticks_t [0x007492D8+438936]
	Microsoft::Applications::Events::time_ticks_t::time_ticks_t [0x0074944B+439307]
	Microsoft::Applications::Events::time_ticks_t::time_ticks_t [0x007318BA+342138]
	BaseThreadInitThunk [0x765B7BA9+25]
	RtlInitializeExceptionChain [0x7709C10B+107]
	RtlClearBits [0x7709C08F+191]

Error processing Cadillac: Message: no such element: Unable to locate element: {"method":"css selector","selector":"div.content"}
  (Session info: MicrosoftEdge=126.0.2592.113)
Stacktrace:
	GetHandleVerifier [0x008736A3+37027]
	Microsoft::Applications::Events::time_ticks_t::time_ticks_t [0x0073FD26+400614]
	Microsoft::Applications::Events::ILogConfiguration::operator* [0x00546DA6+3558]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x0057A6FE+107742]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x0057A87D+108125]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x005A6482+287330]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x00590294+196724]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x00573DB1+80785]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x005A4DD0+281520]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x0058FEB6+195734]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x005735B3+78739]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x005725A5+74629]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x00572FBD+77213]
	GetHandleVerifier [0x0096C0AC+1055404]
	Microsoft::Applications::Events::FromJSON [0x00A446A7+154215]
	Microsoft::Applications::Events::FromJSON [0x00A44047+152583]
	Microsoft::Applications::Events::FromJSON [0x00A34C00+90048]
	Microsoft::Applications::Events::FromJSON [0x00A44EAB+156267]
	Microsoft::Applications::Events::time_ticks_t::time_ticks_t [0x007550BF+487551]
	Microsoft::Applications::Events::time_ticks_t::time_ticks_t [0x007492D8+438936]
	Microsoft::Applications::Events::time_ticks_t::time_ticks_t [0x0074944B+439307]
	Microsoft::Applications::Events::time_ticks_t::time_ticks_t [0x007318BA+342138]
	BaseThreadInitThunk [0x765B7BA9+25]
	RtlInitializeExceptionChain [0x7709C10B+107]
	RtlClearBits [0x7709C08F+191]

Error processing CAMC: Message: no such element: Unable to locate element: {"method":"css selector","selector":"div.content"}

In [101]:
# 1. Count Missing Values:
num_missing = car_brands_df['Brand_logo_URL'].isnull().sum()
print(f"Number of missing Brand_logo_URL values: {num_missing}")

Number of missing Brand_logo_URL values: 72

In [103]:
car_brands_df.to_csv("car_brands_df.csv", index=False)