In [1]:

city_to_city_name = {
    "abilene":"Abilene, TX",
"akron-canton": "Akron-Canton, OH",
"albany, GA":"Albany, GA",
"albany, NY":"Albany, NY",
"albuquerque":"Albuquerque, NM",
"altoona":"Altoona, PA",
"amarillo":"Amarillo, TX",
"ames, IA":"Ames, IA",
"anchorage":"Anchorage, AK",
"annapolis":"Annapolis, MD",
"ann arbor":"Ann Arbor, MI",
"appleton":"Appleton, WI",
"asheville":"Asheville, NC",
"ashtabula":"Ashtabula, OH",
"athens, GA":"Athens, GA",
"athens, OH":"Athens, OH",
"atlanta":"Atlanta, GA",
"auburn":"Auburn, AL",
"augusta":"Augusta, GA",
"austin":"Austin, TX",
"bakersfield":"Bakersfield, CA",
"baltimore":"Baltimore, MD",
"baton rouge":"Baton Rouge, LA",
"battle creek":"Battle Creek, MI",
"beaumont":"Beaumont, TX",
"bellingham":"Bellingham, WA",
"bemidji":"Bemidji, MN",
"bend":"Bend, OR",
"billings":"Billings, MT",
"binghamton":"Binghamton, NY",
"birmingham, AL":"Birmingham, AL",
"bismarck":"Bismarck, ND",
"bloomington, IN":"Bloomington, IN",
"bloomington, IL":"Bloomington, IL",
"boise":"Boise, ID",
"boone":"Boone, NC",
"boston":"Boston, MA",
"boulder":"Boulder, CO",
"bowling green":"Bowling Green, KY",
"bozeman":"Bozeman, MT",
"brainerd":"Brainerd, MN",
"brownsville":"Brownsville, TX",
"brunswick, GA":"Brunswick, GA",
"buffalo":"Buffalo, NY",
"butte":"Butte, MT",
"cape cod":"Cape Cod, MA",
"catskills":"Catskill, NY",
"cedar rapids":"Cedar Rapids, IA",
"central LA":"Central Louisiana Region, LA",
"central MI":"Central Michigan Region, MI",
"central NJ":"Central New Jersey Region, NJ",
"chambana":"Urbana, IL",
"charleston":"Charleston, SC",
"charleston, WV":"Charleston, WV",
"charlotte":"Charlotte, NC",
"charlottesville":"Charlottesville, VA",
"chattanooga":"Chattanooga, TN",
"chautauqua":"Chautauqua, NY",
"chicago":"Chicago, IL",
"chico":"Chico, CA",
"chillicothe":"Chillicothe, OH",
"cincinnati":"Cincinnati, OH",
"clarksville, TN":"Clarksville, TN",
"cleveland":"Cleveland, OH",
"clovis-portales":"Clovis-Portales Area, NM",
"college station":"College Station, TX",
"colo springs":"Colorado Springs, CO",
"columbia, MO":"Columbia, MO",
"columbia":"Columbia, SC",
"columbus, GA":"Columbus, GA",
"columbus, OH":"Columbus, OH",
"cookeville":"Cookeville, TN",
"corpus christi":"Corpus Christi, TX",
"corvallis":"Corvallis, OR",
"cumberland val":"Cumberland Valley Township, PA",
"dallas":"Dallas-Fort Worth Metropolitan Area, TX",
"danville":"Danville, VA",
"daytona beach":"Daytona Beach, FL",
"dayton":"Dayton, OH",
"decatur, IL":"Decatur, IL",
"deep east TX":"Deep East Texas Area, TX",
"delaware":"Delaware, DE",
"del rio":"Del Rio, TX",
"denver":"Denver, CO",
"des moines":"Des Moines, IA",
"detroit metro":"Detroit, MI",
"dothan, AL":"Dothan, AL",
"dubuque":"Dubuque, IA",
"duluth":"Duluth, MN",
"eastern CO":"East Colorado Region, CO",
"eastern CT":"East Connecticut Region, CT",
"eastern KY":"East Kentucky Region, KY",
"eastern montana":"East Montana Region, MT",
"eastern NC":"Eastern Region of North Carolina , NC",
"eastern WV":"Eastern Panhandle Region of West Virginia, WV",
"eastern shore":"Eastern Shore of Maryland, MD",
"east idaho":"Eastern Idaho Region, ID",
"east oregon":"Eastern Oregon Region, OR",
"eau claire":"Eau Claire, WI",
"elko":"Elko, NV",
"elmira":"Elmira, NY",
"el paso":"El Paso, TX",
"erie, PA":"Erie, PA",
"eugene":"Eugene, OR",
"evansville":"Evansville, IN",
"fairbanks":"Fairbanks, AK",
"fargo":"Fargo, ND",
"farmington, NM":"Farmington, NM",
"fayetteville, AR":"Fayetteville, AR",
"fayetteville, NC":"Fayetteville, NC",
"finger lakes":"Finger Lakes, NY",
"flagstaff":"Flagstaff, AZ",
"flint":"Flint, MI",
"the shoals":"Florence-Muscle Shoals Area, AL",
"florence, SC":"Florence, SC",
"florida keys":"Florida Keys, FL",
"fort collins":"Fort Collins, CO",
"fort dodge":"Fort Dodge, IA",
"fort smith":"Fort Smith, AR",
"fort wayne":"Fort Wayne, IN",
"frederick":"Frederick, MD",
"fredericksburg":"Fredericksburg, VA",
"fresno":"Fresno, CA",
"fort myers":"Fort Myers, FL",
"gadsden":"Gadsden, AL",
"gainesville":"Gainesville, FL",
"galveston":"Galveston, TX",
"glens falls":"Glens Falls, NY",
"gold country":"Gold Country Region, CA",
"grand forks":"Grand Forks, ND",
"grand island":"Grand Island, NE",
"grand rapids":"Grand Rapids, MI",
"great falls":"Great Falls, MT",
"green bay":"Green Bay, WI",
"greensboro":"Greensboro, NC",
"greenville":"Greenville, SC",
"gulfport":"Gulfport, MS",
"hanford":"Hanford, CA",
"harrisburg":"Harrisburg, PA",
"harrisonburg":"Harrisonburg, VA",
"hartford":"Hartford, CT",
"hattiesburg":"Hattiesburg, MS",
"hawaii":"Honolulu, HI",
"heartland FL":"Florida Heartland Region, FL",
"helena":"Helena, MT",
"hickory":"Hickory, NC",
"high rockies":"High Rockies Region, CO",
"hilton head":"Hilton Head, SC",
"holland":"Holland, MI",
"houma":"Houma, LA",
"houston":"Houston, TX",
"hudson valley":"Hudson Valley Region, NY",
"humboldt":"Humboldt County, CA",
"huntington":"Huntington, WV",
"huntsville":"Huntsville, AL",
"imperial co":"Imperial County, CA",
"indianapolis":"Indianapolis, IN",
"inland empire":"Inland Empire, CA",
"iowa city":"Iowa City, IA",
"ithaca":"Ithaca, NY",
"jackson, MI":"Jackson, MI",
"jackson, MS":"Jackson, MS",
"jackson, TN":"Jackson, TN",
"jacksonville, FL":"Jacksonville, FL",
"jacksonville, NC":"Jacksonville, NC",
"janesville":"Janesville, WI",
"jersey shore":"Jersey Shore, NJ",
"jonesboro":"Jonesboro, AR",
"joplin":"Joplin, MO",
"kalamazoo":"Kalamazoo, MI",
"kalispell":"Kalispell, MT",
"kansas city":"Kansas City, MO",
"kenai":"Kenai, AK",
"tri-cities, WA":"Tri-Cities, WA",
"kenosha-racine":"Kenosha-Racine, WI",
"killeen-temple":"Killeen-Temple, TX",
"kirksville":"Kirksville, MO",
"klamath falls":"Klamath Falls, OR",
"knoxville":"Knoxville, TN",
"kokomo":"Kokomo, IN",
"la crosse":"La Crosse, WI",
"lafayette":"Lafayette, LA",
"tippecanoe":"Tippecanoe, IN",
"lake charles":"Lake Charles, LA",
"lakeland":"Lakeland, FL",
"lake of ozarks":"Lake of the Ozarks, MO",
"lancaster, PA":"Lancaster, PA",
"lansing":"Lansing, MI",
"laredo":"laredo, TX",
"la salle co":"LaSalle County, IL",
"las cruces":"Las Cruces, NM",
"las vegas":"Las Vegas, NV",
"lawrence":"Lawrence, KS",
"lawton":"Lawton, OK",
"allentown":"Allentown, PA",
"lewiston":"Lewiston, ID",
"lexington":"Lexington, KY",
"lima-findlay":"Lima-Findlay, OH",
"lincoln":"Lincoln, NE",
"little rock":"Little Rock, AR",
"logan":"Logan, UT",
"long island":"Long Island,NY",
"los angeles":"Los Angeles, CA",
"louisville":"Louisville, KY",
"lubbock":"Lubbock, TX",
"lynchburg":"Lynchburg, VA",
"macon":"Macon, GA",
"madison":"Madison, WI",
"maine":"Maine, ME",
"manhattan":"Manhattan, KS",
"mankato":"Mankato, MN",
"mansfield":"Mansfield, OH",
"mason city":"Mason City, IA",
"mattoon":"Mattoon, IL",
"mcallen":"McAllen, TX",
"meadville":"Meadville, PA",
"medford":"Medford, OR",
"memphis":"Memphis, TN",
"mendocino co":"Mendocino County, CA",
"merced":"Merced, CA",
"meridian":"Meridian, MS",
"milwaukee":"Milwaukee, WI",
"minneapolis":"Minneapolis-St Paul Area, MN",
"missoula":"Missoula, MT",
"mobile, AL":"Mobile, AL",
"modesto":"Modesto, CA",
"mohave co":"Mohave County, AZ",
"monroe, LA":"Monroe, LA",
"monroe, MI":"Monroe, MI",
"monterey":"Monterey, CA",
"montgomery":"Montgomery, AL",
"morgantown":"Morgantown, WV",
"moses lake":"Moses Lake, WA",
"muncie":"Muncie, IN",
"muskegon":"Muskegon, MI",
"myrtle beach":"Myrtle Beach, SC",
"nashville":"Nashville, TN",
"new hampshire":"New Hampshire, NH",
"new haven":"New Haven, CT",
"new orleans":"New Orleans, LA",
"blacksburg":"Blacksburg, VA",
"new york":"New York City, NY",
"norfolk":"Norfolk, VA",
"lake city":"Lake City, FL",
"north dakota":"North Dakota Region, ND",
"northeast SD":"Northeast region of South Dakota, SD",
"northern MI":"North region of Michigan, MI",
"northern WV":"North region of West Virginia, WV",
"northern WI":"North region of Wisconsin, WI",
"north jersey":"North Jersey Region, NJ",
"north MS":"North Mississippi Region, MS",
"north platte":"North Platte, NE",
"northwest CT":"North west region of Connecticut, CT",
"northwest GA":"North west region of Georgia, GA",
"northwest KS":"North west region of Kansas, KS",
"northwest OK":"North west region of oklahoma, OK",
"ocala":"Ocala, FL",
"odessa":"Odessa, TX",
"ogden":"Ogden, UT",
"okaloosa":"Okaloosa, FL",
"oklahoma city":"Oklahoma City, OK",
"olympic pen":"Olympic Peninsula, WA",
"omaha":"Omaha, NE",
"oneonta":"Oneonta, NY",
"orange co":"Orange County, CA",
"oregon coast":"Oregon Coast, OR",
"orlando":"Orlando, FL",
"outer banks":"Outer Banks, NC",
"owensboro":"Owensboro, KY",
"palm springs":"Palm Springs, CA",
"panama city, FL":"Panama City, FL",
"parkersburg":"Parkersburg, WV",
"pensacola":"Pensacola, FL",
"peoria":"Peoria, IL",
"philadelphia":"Philadelphia, PA",
"phoenix":"Phoenix, AZ",
"central SD":"Central South Dakota: Missouri River Region, SD",
"pittsburgh":"Pittsburgh, PA",
"plattsburgh":"Plattsburgh, NY",
"poconos":"Poconos, PA",
"port huron":"Port Huron, MI",
"portland":"Portland, OR",
"potsdam-massena":"Potsdam-Canton-Massena, NY",
"prescott":"Prescott, AZ",
"provo":"Provo, UT",
"pueblo":"Pueblo, CO",
"pullman-moscow":"Pullman-Moscow, WA",
"quad cities":"Davenport, IA",
"raleigh":"Raleigh, NC",
"rapid city":"Rapid City,, SD",
"reading":"Reading, PA",
"redding":"Redding, CA",
"reno":"Reno, NV",
"rhode island":"Rhode Island, RI",
"richmond, IN":"Richmond, IN",
"richmond, VA":"Richmond, VA",
"roanoke":"Roanoke, VA",
"rochester, MN":"Rochester, MN",
"rochester, NY":"Rochester, NY",
"rockford":"Rockford, IL",
"roseburg":"Roseburg, OR",
"roswell":"Roswell, NM",
"sacramento":"Sacramento, CA",
"saginaw":"Saginaw, MI",
"salem":"Salem, OR",
"salina":"Salina, KS",
"salt lake":"Salt Lake City, UT",
"san angelo":"San Angelo, TX",
"san antonio":"San Antonio, TX",
"san diego":"San Diego, CA",
"sandusky":"Sandusky, OH",
"san luis obispo":"San Luis Obispo, CA",
"san marcos":"San Marcos, TX",
"santa barbara":"Santa Barbara, CA",
"santa fe":"Santa Fe, NM",
"santa maria":"Santa Maria, CA",
"sarasota":"Sarasota, FL",
"savannah":"Savannah, GA",
"scottsbluff":"Scottsbluff, NE",
"scranton":"Scranton, PA",
"seattle":"Seattle, WA",
"SF bay area":"San Francisco - Bay Area, CA",
"sheboygan, WI":"Sheboygan, WI",
"show low":"Show Low, AZ",
"shreveport":"Shreveport, LA",
"sierra vista":"Sierra Vista, AZ",
"sioux city":"Sioux City, IA",
"sioux falls":"Sioux Falls, SD",
"siskiyou co":"Siskiyou County, CA",
"skagit":"Skagit, WA",
"south bend":"South Bend, IN",
"south coast":"Southern Bristol and Plymouth counties, MA",
"south dakota":"South Dakota, SD",
"southeast AK":"South Eastern Region of Alaska, AK",
"southeast IA":"South Eastern Region of Iowa, IA",
"southeast KS":"South Eastern Region of Kansas, KS",
"southeast MO":"South Eastern Region of Missouri, MO",
"southern IL":"South Region of Illinois, IL",
"southern MD":"South Region of Maryland, MD",
"southern WV":"South Region of West Virginia, WV",
"south florida":"Miami, FL",
"south jersey":"South Region of New Jersey, NJ",
"southwest KS":"South West Region of Kansas, KS",
"southwest MI":"South West Region of Maryland, MI",
"southwest MN":"South Western Region of Minnesota, MN",
"southwest MS":"South Western Region of Mississippi, MS",
"southwest TX":"South Western Region of Texas, TX",
"southwest VA":"South Western Region of Virginia, VA",
"space coast":"Space Coast, FL",
"spokane":"Spokane, WA",
"springfield, IL":"Springfield, IL",
"springfield":"Springfield, MO",
"state college":"State College, PA",
"statesboro":"Statesboro, GA",
"st augustine":"St Augustine, FL",
"st cloud":"St Cloud, MN",
"st george":"St George, UT",
"stillwater":"Stillwater, OK",
"st joseph":"St Joseph, MO",
"st louis":"st louis, MO",
"stockton":"Stockton, CA",
"susanville":"Susanville, CA",
"syracuse":"Syracuse, NY",
"tallahassee":"Tallahassee, FL",
"tampa bay":"Tampa, FL",
"terre haute":"Terre Haute, IN",
"texarkana":"Texarkana, TX",
"texoma":"Texoma, TX",
"the thumb":"The Thumb, MI",
"toledo":"Toledo, OH",
"topeka":"Topeka, KS",
"treasure coast":"Treasure Coast, FL",
"tri-cities, TN":"Tri-Cities Region, TN",
"tucson":"Tucson, AZ",
"tulsa":"Tulsa, OK",
"tuscaloosa":"Tuscaloosa, AL",
"tuscarawas co":"Tuscarawas County, OH",
"twin falls":"Twin Falls, ID",
"twin tiers":"Twin Tiers, NY",
"east TX":"Tyler, TX",
"yoopers":"Upper Peninsula, MI",
"utica":"Utica, NY",
"valdosta":"Valdosta, GA",
"ventura":"Ventura County, CA",
"vermont":"Vermont, VT",
"victoria, TX":"Victoria, TX",
"visalia-tulare":"Visalia-Tulare, CA",
"waco":"Waco, TX",
"washington, DC":"Washington, DC",
"waterloo":"Waterloo, IA",
"watertown":"Watertown, NY",
"wausau":"Wausau, WI",
"wenatchee":"Wenatchee, WA",
"western IL":"Western Illinois Region, IL",
"western KY":"Western Kentucky Region, KY",
"western MD":"Western Maryland Region, MD",
"western mass":"Western Massachusetts Region, MA",
"western slope":"Western Slope, CO",
"west virginia":"West Virginia, WV",
"wichita falls":"Wichita Falls, TX",
"wichita":"wichita, KS",
"williamsport":"Williamsport, PA",
"wilmington, NC":"Wilmington, NC",
"winchester":"Winchester, VA",
"winston-salem":"Winston-Salem,NC",
"worcester":"Worcester, MA",
"wyoming":"Wyoming, WY",
"yakima":"Yakima, WA",
"york, PA":"York, PA",
"youngstown":"Youngstown, OH",
"yuba-sutter":"Yuba-Sutter, CA",
"yuma":"Yuma, AZ",
"zanesville":"Zanesville, OH"
}

state_abbv_to_state_name = {
    "AL":"ALABAMA",
    "AK":"ALASKA",
    "AZ":"ARIZONA",
    "AR":"ARKANSAS",
    "AS":"AMERICAN SAMOA",
    "CA":"CALIFORNIA",
    "CO":"COLORADO",
    "CT":"CONNECTICUT",
    "DE":"DELAWARE",
    "DC":"DISTRICT OF COLUMBIA",
    "FL":"FLORIDA",
    "AL":"GEORGIA",
    "GU":"GUAM",
    "HI":"HAWAII",
    "ID":"IDAHO",
    "AL":"ILLINOIS",
    "IN":"INDIANA",
    "IA":"IOWA",
    "KS":"KANSAS",
    "KY":"KENTUCKY",
	"LA":"LOUISIANA",
	"ME":"MAINE",
	"MD":"MARYLAND",
	"MA":"MASSACHUSETTS",
	"MI":"MICHIGAN",
	"MN":"MINNESOTA",
	"MS":"MISSISSIPPI",
	"MO":"MISSOURI",
	"MT":"MONTANA",
	"NE":"NEBRASKA",
	"NV":"NEVADA",
	"NH":"NEW HAMPSHIRE",
	"NJ":"NEW JERSEY",
	"NM":"NEW MEXICO",
	"NY":"NEW YORK",
	"NC":"NORTH CAROLINA",
	"ND":"NORTH DAKOTA",
	"MP":"NORTHERN MARIANA IS",
	"OH":"OHIO",
	"OK":"OKLAHOMA",
	"OR":"OREGON",
	"PA":"PENNSYLVANIA",
	"PR":"PUERTO RICO",
	"RI":"RHODE ISLAND",
	"SC":"SOUTH CAROLINA",
	"SD":"SOUTH DAKOTA",
	"TN":"TENNESSEE",
	"TX":"TEXAS",
	"UT":"UTAH",
	"VT":"VERMONT",
 	"VA":"VIRGINIA",
	"VI":"VIRGIN ISLANDS",
	"WA":"WASHINGTON",
	"WV":"WEST VIRGINIA",
	"WI":"WISCONSIN",
	"WY":"WYOMING"
}

In [2]:

from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.firefox.options import Options
from selenium.webdriver import Firefox
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.common.exceptions import TimeoutException, NoSuchElementException
from selenium.common.exceptions import WebDriverException
from time import sleep
import warnings
import requests
import pandas as pd
from bs4 import BeautifulSoup
import time
import math
import re

import sqlite3


from datetime import datetime, timedelta

import numpy as np
import pyodbc as odbc
from sqlalchemy import create_engine
import sqlalchemy as sa

warnings.filterwarnings('ignore')

In [3]:
print(odbc.drivers())

['SQL Server', 'Microsoft Access Driver (*.mdb, *.accdb)', 'Microsoft Excel Driver (*.xls, *.xlsx, *.xlsm, *.xlsb)', 'Microsoft Access Text Driver (*.txt, *.csv)']

In [4]:
# Get the current date
current_date = (datetime.now()).strftime("%d_%m_%Y")  # - timedelta(days = 1)
cd= (datetime.now()).strftime("%m_%d_%Y")

In [5]:
postings_df_matched_rows = pd.read_csv(f'W:/Personal Projects/UCPP/Notebooks/Data/postings/posting_df_{current_date}.csv')

In [6]:
postings_df_matched_rows.head()

,Unnamed: 0,index,City,URL,Title,Price,Tags
0,0,0,abilene,https://abilene.craigslist.org/cto/d/abilene-2...,2018 Explorer XLT FWD,"$20,250",2h ago·91k mi·Abilene
1,1,1,abilene,https://abilene.craigslist.org/ctd/d/eastland-...,2017 Kia Forte LX !BUY HERE PAY HERE! Financia...,NaN,5h ago·124k mi·Eastland - MOTHER'S DAY SALE
2,2,2,abilene,https://abilene.craigslist.org/ctd/d/eastland-...,2018 Chevrolet Sonic LS !BUY HERE PAY HERE! Co...,NaN,5h ago·82k mi·Eastland - MOTHER'S DAY SALE
3,3,3,abilene,https://abilene.craigslist.org/ctd/d/eastland-...,2016 Dodge Dart SXT !BUY HERE PAY HERE! Financ...,NaN,6h ago·70k mi·Eastland - MOTHER'S DAY SALE
4,4,4,abilene,https://abilene.craigslist.org/ctd/d/eastland-...,2014 Ford F-150 XLT !BUY HERE PAY HERE! Financ...,NaN,6h ago·114k mi·Eastland - MOTHER'S DAY SALE

In [7]:
len(postings_df_matched_rows)

14658

In [8]:
current_date

'02_05_2024'

In [10]:
options = Options()
options.add_argument("--window-size=1920x1080")
options.add_argument("--headless")  # Headless mode
options.add_argument("--verbose")

browser = Firefox(options=options)
browser.set_page_load_timeout(30)

# Function to scrape car attributes
def scrape_car_attributes(browser, url):
    car_attributes = {'Posting_URL': url}  # Include URL in the attributes for tracking
    try:
        browser.get(url)
        WebDriverWait(browser, 10).until(EC.presence_of_element_located((By.ID, 'postingbody')))
        posting_content = browser.find_element(By.ID, 'postingbody')
        car_attributes['Post Content'] = posting_content.text
        # Add other scraping logic here
        # Add other scraping logic here
        all_content = browser.find_elements(By.CSS_SELECTOR,'div.mapAndAttrs')
        for i in all_content:
                   
            manuf_year = i.find_element(By.CSS_SELECTOR, 'span.valu.year') if i.find_elements(By.CSS_SELECTOR, 'span.valu.year') else None
            car_attributes['Manufacturing Year'] = manuf_year.text
            

            # Find the manufacturer and model name
            manuf_model_element = i.find_element(By.CSS_SELECTOR, 'a.valu.makemodel') if i.find_elements(By.CSS_SELECTOR, 'a.valu.makemodel') else None
            if manuf_model_element:
                parts = manuf_model_element.text.split(" ")
                parts = [part for part in parts if not part.isnumeric()]  # Remove numeric parts (like years)
                if len(parts) >= 2:
                    # Assuming the first non-numeric part is the manufacturer and the rest is the model 
                    car_attributes['Manufacturer'] = parts[0]
                    car_attributes['Model Name'] = " ".join(parts[1:])
                elif len(parts) == 1:
                    # In case there's only one part, we'll use it as the model name
                    # This is a simplification and may not be accurate for all cases
                    car_attributes['Manufacturer'] = None
                    car_attributes['Model Name'] = parts[0]
            else:
                car_attributes['Manufacturer'] = None
                car_attributes['Model Name'] = None
            
            # End of the correction space
            y = i.find_elements(By.CSS_SELECTOR, 'div.attrgroup')
            zm = y[1].text
            lines = zm.splitlines()            

            for line in lines:
                if not line.strip():
                    continue
                key,value = line.split(":", 1)

                key = key.strip()
                
                #Add the key - value pair to the dictionary
                car_attributes[key] = value.strip()

    except WebDriverException as e:
        # Instead of printing the error, return a code or simple message
        car_attributes['Error'] = 'Page not found or element missing'
    return car_attributes

In [12]:
options = Options()
options.add_argument("--window-size=1920x1080")
options.add_argument("--headless")  # Headless mode
options.add_argument("--verbose")

browser = Firefox(options=options)
browser.set_page_load_timeout(30)

url = postings_df_matched_rows.iloc[4590]['URL']
car_attributes = {'Posting_URL': url}

In [15]:
browser.get(url)
WebDriverWait(browser, 10).until(EC.presence_of_element_located((By.ID, 'postingbody')))
posting_content = browser.find_element(By.ID, 'postingbody')
car_attributes['Post Content'] = posting_content.text
# Add other scraping logic here
# Add other scraping logic here
all_content = browser.find_elements(By.CSS_SELECTOR,'div.mapAndAttrs')

In [17]:
all_content

In [16]:
manuf_year = i.find_element(By.CSS_SELECTOR, 'span.valu.year') if i.find_elements(By.CSS_SELECTOR, 'span.valu.year') else None
car_attributes['Manufacturing Year'] = manuf_year.text


# Find the manufacturer and model name
manuf_model_element = i.find_element(By.CSS_SELECTOR, 'a.valu.makemodel') if i.find_elements(By.CSS_SELECTOR, 'a.valu.makemodel') else None

StaleElementReferenceException: Message: The element with the reference d64d6866-dbe0-4ead-9563-c8c98f6942cc is stale; either its node document is not the active document, or it is no longer connected to the DOM; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#stale-element-reference-exception
Stacktrace:
RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8
WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:193:5
StaleElementReferenceError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:725:5
getKnownElement@chrome://remote/content/marionette/json.sys.mjs:401:11
deserializeJSON@chrome://remote/content/marionette/json.sys.mjs:259:20
cloneObject@chrome://remote/content/marionette/json.sys.mjs:59:24
deserializeJSON@chrome://remote/content/marionette/json.sys.mjs:289:16
cloneObject@chrome://remote/content/marionette/json.sys.mjs:59:24
deserializeJSON@chrome://remote/content/marionette/json.sys.mjs:289:16
json.deserialize@chrome://remote/content/marionette/json.sys.mjs:293:10
receiveMessage@chrome://remote/content/marionette/actors/MarionetteCommandsChild.sys.mjs:72:30

In [ ]:
for i in all_content:
            
    manuf_year = i.find_element(By.CSS_SELECTOR, 'span.valu.year') if i.find_elements(By.CSS_SELECTOR, 'span.valu.year') else None
    car_attributes['Manufacturing Year'] = manuf_year.text
    

    # Find the manufacturer and model name
    manuf_model_element = i.find_element(By.CSS_SELECTOR, 'a.valu.makemodel') if i.find_elements(By.CSS_SELECTOR, 'a.valu.makemodel') else None
    if manuf_model_element:
        parts = manuf_model_element.text.split(" ")
        parts = [part for part in parts if not part.isnumeric()]  # Remove numeric parts (like years)
        if len(parts) >= 2:
            # Assuming the first non-numeric part is the manufacturer and the rest is the model 
            car_attributes['Manufacturer'] = parts[0]
            car_attributes['Model Name'] = " ".join(parts[1:])
        elif len(parts) == 1:
            # In case there's only one part, we'll use it as the model name
            # This is a simplification and may not be accurate for all cases
            car_attributes['Manufacturer'] = None
            car_attributes['Model Name'] = parts[0]
    else:
        car_attributes['Manufacturer'] = None
        car_attributes['Model Name'] = None
    
    # End of the correction space
    y = i.find_elements(By.CSS_SELECTOR, 'div.attrgroup')
    zm = y[1].text
    lines = zm.splitlines()   
    filtered_lines = [line for line in lines if ':' in line]

In [26]:
print(filtered_lines)

['VIN: 2C3CDXL90KH712239', 'condition: like new', 'cylinders: 8 cylinders', 'drive: rwd', 'fuel: gas', 'odometer: 14200', 'paint color: white', 'title status: clean', 'transmission: automatic', 'type: sedan']

In [27]:
for line in filtered_lines:
    if not line.strip():
        continue
    key,value = line.split(":", 1)

    key = key.strip()
    
    #Add the key - value pair to the dictionary
    car_attributes[key] = value.strip()

In [14]:
 # Include URL in the attributes for tracking
try:
    browser.get(url)
    WebDriverWait(browser, 10).until(EC.presence_of_element_located((By.ID, 'postingbody')))
    posting_content = browser.find_element(By.ID, 'postingbody')
    car_attributes['Post Content'] = posting_content.text
    # Add other scraping logic here
    # Add other scraping logic here
    all_content = browser.find_elements(By.CSS_SELECTOR,'div.mapAndAttrs')
    for i in all_content:
                
        manuf_year = i.find_element(By.CSS_SELECTOR, 'span.valu.year') if i.find_elements(By.CSS_SELECTOR, 'span.valu.year') else None
        car_attributes['Manufacturing Year'] = manuf_year.text
        

        # Find the manufacturer and model name
        manuf_model_element = i.find_element(By.CSS_SELECTOR, 'a.valu.makemodel') if i.find_elements(By.CSS_SELECTOR, 'a.valu.makemodel') else None
        if manuf_model_element:
            parts = manuf_model_element.text.split(" ")
            parts = [part for part in parts if not part.isnumeric()]  # Remove numeric parts (like years)
            if len(parts) >= 2:
                # Assuming the first non-numeric part is the manufacturer and the rest is the model 
                car_attributes['Manufacturer'] = parts[0]
                car_attributes['Model Name'] = " ".join(parts[1:])
            elif len(parts) == 1:
                # In case there's only one part, we'll use it as the model name
                # This is a simplification and may not be accurate for all cases
                car_attributes['Manufacturer'] = None
                car_attributes['Model Name'] = parts[0]
        else:
            car_attributes['Manufacturer'] = None
            car_attributes['Model Name'] = None
        
        # End of the correction space
        y = i.find_elements(By.CSS_SELECTOR, 'div.attrgroup')
        zm = y[1].text
        lines = zm.splitlines()            

        for line in lines:
            if not line.strip():
                continue
            key,value = line.split(":", 1)

            key = key.strip()
            
            #Add the key - value pair to the dictionary
            car_attributes[key] = value.strip()

except WebDriverException as e:
    # Instead of printing the error, return a code or simple message
    car_attributes['Error'] = 'Page not found or element missing'

AttributeError: 'NoneType' object has no attribute 'text'

In [ ]:

posting_attributes = []

In [ ]:

# Assume df2_without_duplicates is already defined and it's the DataFrame you want to process


# Iterate over the DataFrame rows
for index, row in postings_df_matched_rows.iterrows():
    print(f"Scraping row {index} and URL: {row['URL']}")
    attributes = scrape_car_attributes(browser, row['URL'])
    posting_attributes.append(attributes)

browser.quit()  # Make sure to quit the browser after the loop

# Assign the list of results to the 'Posting_Attributes' column
postings_df_matched_rows['Posting_Attributes'] = posting_attributes

# The rest of your DataFrame manipulation and saving code goes here

# Normalize the 'Posting_Attributes' column to create a DataFrame where keys of dictionaries become columns.
attributes_df = pd.json_normalize(postings_df_matched_rows['Posting_Attributes'])

# Join the new attributes DataFrame with the original df2 DataFrame.
# This assumes that df2's index aligns with the attributes_df's index.
detailed_postings_df = postings_df_matched_rows.join(attributes_df)

# Replace NaN values with 'N/A' or any other placeholder you prefer.
detailed_postings_df.fillna('N/A', inplace=True)

# Use the formatted date in the filename
scraped_data_filename = f'W:/Personal Projects/UCPP/Notebooks/Data/scraped_data/scraped_data_{current_date}.csv' 

# Save the DataFrame to CSV with the dynamic filename
detailed_postings_df.to_csv(scraped_data_filename)

In [9]:
len(posting_attributes)

15804

In [ ]:
#error index - 
# Define the starting index
start_index = 12231

# Iterate over the DataFrame rows starting from the start_index
for index, row in postings_df_matched_rows.iterrows():
    if index < start_index:
        continue  # Skip rows until reaching the start_index
    print(f"Scraping row {index} and URL: {row['URL']}")
    attributes = scrape_car_attributes(browser, row['URL'])
    posting_attributes.append(attributes)

browser.quit()  # Make sure to quit the browser after the loop

In [ ]:
# Assuming postings_df_matched_rows is your DataFrame
postings_df_matched_rows = postings_df_matched_rows.drop(12231)

In [ ]:
# Assign the list of results to the 'Posting_Attributes' column
# Note: This will overwrite any existing 'Posting_Attributes', consider appending or merging if needed.
postings_df_matched_rows['Posting_Attributes'] = posting_attributes

In [ ]:

# Normalize the 'Posting_Attributes' column to create a DataFrame where keys of dictionaries become columns.
attributes_df = pd.json_normalize(postings_df_matched_rows['Posting_Attributes'])

# Join the new attributes DataFrame with the original df2 DataFrame.
# This assumes that df2's index aligns with the attributes_df's index.
detailed_postings_df = postings_df_matched_rows.join(attributes_df)

# Replace NaN values with 'N/A' or any other placeholder you prefer.
detailed_postings_df.fillna('N/A', inplace=True)

In [10]:
# Convert cd to a datetime object
cd_datetime = pd.to_datetime(cd, format='%m_%d_%Y')

# Assign the datetime object to the 'Date' column of detailed_postings_df
detailed_postings_df['Date'] = cd_datetime

In [11]:
len(detailed_postings_df[detailed_postings_df['Error'] == 'Page not found or element missing'])

98

In [12]:
len(detailed_postings_df[detailed_postings_df['Error'] != 'Page not found or element missing'])

15706

In [13]:
detailed_postings_df.columns

Index(['Unnamed: 0', 'index', 'City', 'URL', 'Title', 'Price', 'Tags',
       'Posting_Attributes', 'Posting_URL', 'Post Content',
       'Manufacturing Year', 'Manufacturer', 'Model Name', 'fuel', 'odometer',
       'title status', 'transmission', 'condition', 'cylinders', 'drive',
       'paint color', 'type', 'VIN', 'Error', 'Date'],
      dtype='object')

In [14]:
# Function to lookup state
def lookup_city_name(city):
    return city_to_city_name.get(city, None)  # Returns None if the city is not found

# Function to lookup state
def lookup_state_name(state):
    return state_abbv_to_state_name.get(state, None)  # Returns None if the city is not found

# Function to extract state abbreviation from city names
def extract_state_abbreviation(city):
    # Split the city name by comma and strip any leading/trailing whitespace
    parts = city.split(',')
    if len(parts) > 1:
        # Return the state abbreviation, which is the second part after splitting
        return parts[1].strip()
    else:
        # Return None if there's no comma (and thus no state abbreviation)
        return None


detailed_postings_df['City Name'] = detailed_postings_df['City'].apply(lookup_city_name)
# Apply the function to the City column to create a new State column
detailed_postings_df['State'] = detailed_postings_df['City Name'].apply(extract_state_abbreviation)
detailed_postings_df['State Name'] = detailed_postings_df['State'].apply(lookup_state_name)

In [15]:
detailed_postings_df['City Name'].isna().sum()

0

In [16]:
detailed_postings_df['State'].isna().sum()

0

In [17]:
idead_table_columns_df = detailed_postings_df[detailed_postings_df['Error'] != 'Page not found or element missing'][['City', 'URL', 'Title', 'Price', 'Tags',
       'Posting_Attributes', 'Post Content','Manufacturing Year', 'Manufacturer',
       'Model Name', 'fuel', 'odometer','title status', 'transmission', 'cylinders', #'size',
       'drive', 'type','condition', 'paint color', 'VIN',  'Date', 'State', 'State Name', 'City Name']]

In [18]:
idead_table_columns_df = idead_table_columns_df.fillna('NA')

In [19]:
# Convert 'odometer' column to float, setting non-convertible values to NaN
idead_table_columns_df['odometer'] = pd.to_numeric(idead_table_columns_df['odometer'], errors='coerce')
# Convert 'odometer' column to float, setting non-convertible values to NaN
idead_table_columns_df['Manufacturing Year'] = pd.to_numeric(idead_table_columns_df['Manufacturing Year'], errors='coerce')

idead_table_columns_df['size'] = 'NA'

In [20]:
len(idead_table_columns_df)

15706

In [21]:
idead_table_columns_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 15706 entries, 0 to 15803
Data columns (total 25 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   City                15706 non-null  object
 1   URL                 15706 non-null  object
 2   Title               15706 non-null  object
 3   Price               15706 non-null  object
 4   Tags                15706 non-null  object
 5   Posting_Attributes  15706 non-null  object
 6   Post Content        15706 non-null  object
 7   Manufacturing Year  15706 non-null  int64
 8   Manufacturer        15706 non-null  object
 9   Model Name          15706 non-null  object
 10  fuel                15706 non-null  object
 11  odometer            15550 non-null  float64
 12  title status        15706 non-null  object
 13  transmission        15706 non-null  object
 14  cylinders           15706 non-null  object
 15  drive               15706 non-null  object
 16  type                15706 non-null  object
 17  condition           15706 non-null  object
 18  paint color         15706 non-null  object
 19  VIN                 15706 non-null  object
 20  Date                15706 non-null  datetime64[ns]
 21  State               15706 non-null  object
 22  State Name          15706 non-null  object
 23  City Name           15706 non-null  object
 24  size                15706 non-null  object
dtypes: datetime64[ns](1), float64(1), int64(1), object(22)
memory usage: 3.1+ MB

In [22]:
idead_table_columns_df.head()

,City,URL,Title,Price,Tags,Posting_Attributes,Post Content,Manufacturing Year,Manufacturer,Model Name,...,drive,type,condition,paint color,VIN,Date,State,State Name,City Name,size
0,abilene,https://abilene.craigslist.org/ctd/d/abilene-2...,2016 Kia Forte,N/A,4h ago·92k mi,{'Posting_URL': 'https://abilene.craigslist.or...,"$1,500 Down with Approved Credit\n\n2016 Kia F...",2016,kia,forte,...,N/A,N/A,N/A,N/A,N/A,2024-04-11,TX,TEXAS,"Abilene, TX",NA
1,abilene,https://abilene.craigslist.org/cto/d/knox-city...,2013 f250 platnium 580-600 hp,"$26,500",5h ago·213k mi·Knox city,{'Posting_URL': 'https://abilene.craigslist.or...,2013 f250 platnium with a good amount of stuff...,2013,f250,platnium,...,4wd,pickup,good,grey,N/A,2024-04-11,TX,TEXAS,"Abilene, TX",NA
2,abilene,https://abilene.craigslist.org/cto/d/perris-ke...,Kenworth t600,"$16,800",4/11·735k mi·Ubicación del camión Perris Calif...,{'Posting_URL': 'https://abilene.craigslist.or...,"Vendo mi Kenworth 2007 título limpio 735,000 m...",2007,kenworth,t600,...,N/A,N/A,good,N/A,N/A,2024-04-11,TX,TEXAS,"Abilene, TX",NA
3,abilene,https://abilene.craigslist.org/ctd/d/rancho-co...,2022 Mercedes-Benz S-Class S 580 4MATIC AWD 4d...,"$89,985",4/11·24k mi·+ Sacramento Luxury Motors,{'Posting_URL': 'https://abilene.craigslist.or...,2022 Mercedes-Benz S-Class S 580 4MATIC AWD 4d...,2022,MERCEDES-BENZ,S-CLASS,...,N/A,sedan,N/A,white,W1K6G7GB4NA087527,2024-04-11,TX,TEXAS,"Abilene, TX",NA
4,abilene,https://abilene.craigslist.org/ctd/d/rancho-co...,N/A,N/A,N/A,{'Posting_URL': 'https://abilene.craigslist.or...,2022 Mercedes-Benz S-Class S 580 4MATIC AWD 4d...,2022,MERCEDES-BENZ,S-CLASS,...,N/A,sedan,N/A,white,W1K6G7GB4NA087527,2024-04-11,TX,TEXAS,"Abilene, TX",NA

In [23]:
import json

# Convert the 'Posting_Attributes' column to a JSON string
idead_table_columns_df['Posting_Attributes'] = idead_table_columns_df['Posting_Attributes'].apply(lambda x: json.dumps(x) if isinstance(x, dict) else x)

In [24]:
connection = sqlite3.connect('UCPP_test.db')

In [25]:
cursor = connection.cursor()

table_name = 'used_cars'
query = f"SELECT * FROM {table_name}"

df = pd.read_sql_query(query, connection)

len(df)

392087

In [26]:
idead_table_columns_df.to_sql('used_cars', connection, if_exists='append')

15706

In [27]:
table_name = 'used_cars'
query = f"SELECT * FROM {table_name}"

df = pd.read_sql_query(query, connection)

len(df)

407793